SootopolisCity_House5_MapScripts::
	.byte 0

SootopolisCity_House5_EventScript_Maniac::
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl::
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection:
    .string "נראה שיש קשר מסוים\n"
    .string "בין סוטופוליס להר המוקד.\p"
    .string "חבריי ואני עשינו כמה מחקרים על\n"
    .string "זה במעבדה שבה עבדתי.$"

SootopolisCity_House5_Text_BrotherUsedToStudySea:
	.string "האח הגדול שלי היה לומד על הים.$"

