RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "בית הספר למאמנים הוא מצויין.\p"
	.string "אם תלמד{ADD_YUD} שם, תוכל{ADD_YUD} אפילו\n"
	.string "להיות מנהיג{ADD_TAF} מכון.$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "רוקסן, מנהיגת המכון, יודעת\n"
	.string "הרבה על פוקימון.\p"
	.string "היא גם ממש חזקה!$"

