PacifidlogTown_House1_MapScripts::
	.byte 0

PacifidlogTown_House1_EventScript_Man::
	msgbox PacifidlogTown_House1_Text_RegiStory, MSGBOX_NPC
	end

PacifidlogTown_House1_EventScript_Woman::
	msgbox PacifidlogTown_House1_Text_SixDotsOpenThreeDoors, MSGBOX_NPC
	end

PacifidlogTown_House1_Text_RegiStory:
	.string "במחוז הואן, ישנם שלושה פוקימונים\n"
	.string "שמייצגים כוח של אבן, קרח ופלדה.\p"
	.string "אומרים שכל אחד מהם מסתתר עמוק בתוך\n"
	.string "מערות.\p"
	.string "זה הסיפור ששמעתי כשהייתי\n"
	.string "ילד קטן.$"

PacifidlogTown_House1_Text_SixDotsOpenThreeDoors:
	.string "”שש נקודות פותחות שלוש דלתות.“\p"
	.string "סבא נהג לומר את זה, אבל אני לא\n"
	.string "יודעת למה הוא התכוון.$"

