BattleDome_Text_Potential1::
	.string "המועמד הטוב ביותר להיות אלוף!$"

BattleDome_Text_Potential2::
	.string "קבוצה מובטחת לגמר.$"

BattleDome_Text_Potential3::
	.string "סביר שתסיים בין שלושת הראשונים.$"

BattleDome_Text_Potential4::
	.string "מועמד לסיים ראשון.$"

BattleDome_Text_Potential5::
	.string "קבוצה עם פוטנציאל מהשורה הראשונה.$"

BattleDome_Text_Potential6::
	.string "קבוצת הסוס השחור של הטורניר הזה.$"

BattleDome_Text_Potential7::
	.string "קבוצה טובה מהממוצע.$"

BattleDome_Text_Potential8::
	.string "קבוצת הטורניר הממוצעת.$"

BattleDome_Text_Potential9::
	.string "קבוצה עם פוטנציאל ממוצע.$"

BattleDome_Text_Potential10::
	.string "קבוצה חלשה מהממוצע.$"

BattleDome_Text_Potential11::
	.string "קבוצה שמחפשת את ניצחונה הראשון.$"

BattleDome_Text_Potential12::
	.string "ניצחון אחד יעשה לקבוצה הזו גאווה.$"

BattleDome_Text_Potential13::
	.string "בסך הכל, קבוצה חלשה.$"

BattleDome_Text_Potential14::
	.string "קבוצה עם פוטנציאל נמוך מאוד.$"

BattleDome_Text_Potential15::
	.string "קבוצה שלא צפויה לנצח בטורניר.$"

BattleDome_Text_Potential16::
	.string "הקבוצה שפחות צפוי שתנצח.$"

BattleDome_Text_PotentialDomeAceTucker::
	.string "הכוכב המושלם והבלתי מנוצח!$"

BattleDome_Text_StyleRiskDisaster::
	.string "מוכן לקחת סיכונים שיכולים להוביל לאסון.$"

BattleDome_Text_StyleEndureLongBattles::
	.string "מומחה בהתמודדות עם קרבות ארוכים.$"

BattleDome_Text_StyleVariesTactics::
	.string "משנה את הטקטיקות בהתאם ליריב.$"

BattleDome_Text_StyleToughWinningPattern::
	.string "יש לו דפוס ניצחון קשוח.$"

BattleDome_Text_StyleUsesVeryRareMove::
	.string "לפעמים משתמש במהלך נדיר מאוד.$"

BattleDome_Text_StyleUsesStartlingMoves::
	.string "משתמש במהלכים מפתיעים ומפריעים.$"

BattleDome_Text_StyleConstantlyWatchesHP::
	.string "עוקב כל הזמן אחרי הנח בקרב.$"

BattleDome_Text_StyleStoresAndLoosesPower::
	.string "טוב באגירת כוח ואז שחרורו.$"

BattleDome_Text_StyleEnfeeblesFoes::
	.string "מומחה בהחלשת יריבים.$"

BattleDome_Text_StylePrefersLuckTactics::
	.string "מעדיף טקטיקות שתלויות במזל.$"

BattleDome_Text_StyleRegalAtmosphere::
	.string "תוקף באווירה מלכותית.$"

BattleDome_Text_StylePowerfulLowPPMoves::
	.string "תוקף במהלכים רבי עוצמה עם נכ נמוכות.$"

BattleDome_Text_StyleEnfeebleThenAttack::
	.string "מומחה בהחלשה ואז התקפה.$"

BattleDome_Text_StyleBattlesWhileEnduring::
	.string "נלחם תוך סבילה של כל ההתקפות.$"

BattleDome_Text_StyleUpsetsFoesEmotionally::
	.string "מומחה בהפרעה רגשית ליריבים.$"

BattleDome_Text_StyleStrongAndStraightforward::
	.string "משתמש במהלכים חזקים וישירים.$"

BattleDome_Text_StyleAggressivelyStrongMoves::
	.string "משתמש באופן אגרסיבי במהלכים חזקים.$"

BattleDome_Text_StyleCleverlyDodgesAttacks::
	.string "נלחם תוך התחמקות חכמה מהתקפות.$"

BattleDome_Text_StyleUsesUpsettingMoves::
	.string "מומחה בשימוש במהלכים שמפריעים.$"

BattleDome_Text_StyleUsesPopularMoves::
	.string "משתמש בהרבה מהלכים פופולריים.$"

BattleDome_Text_StyleHasPowerfulComboMoves::
	.string "יש לו מהלכים לשילובים חזקים.$"

BattleDome_Text_StyleUsesHighProbabilityMoves::
	.string "משתמש בהתקפות עם סיכוי גבוה.$"

BattleDome_Text_StyleAggressivelySpectacularMoves::
	.string "משתמש באופן אגרסיבי במהלכים מרהיבים.$"

BattleDome_Text_StyleEmphasizesOffenseOverDefense::
	.string "מתמקד בהתקפה על פני הגנה.$"

BattleDome_Text_StyleEmphasizesDefenseOverOffense::
	.string "מתמקד בהגנה על פני תקיפה.$"

BattleDome_Text_StyleAttacksQuicklyStrongMoves::
	.string "תוקף במהירות במהלכים חזקים.$"

BattleDome_Text_StyleUsesAddedEffectMoves::
	.string "לעיתים משתמש במהלכים עם השפעה נוספת.$"

BattleDome_Text_StyleUsesBalancedMixOfMoves::
	.string "משתמש בתערובת מאוזנת של מהלכים.$"

BattleDome_Text_StyleSampleMessage1::
	.string "זהו הודעת דוגמה 1.$"

BattleDome_Text_StyleSampleMessage2::
	.string "זהו הודעת דוגמה 2.$"

BattleDome_Text_StyleSampleMessage3::
	.string "זהו הודעת דוגמה 3.$"

BattleDome_Text_StyleSampleMessage4::
	.string "זהו הודעת דוגמה 4.$"

BattleDome_Text_EmphasizesHPAndAtk::
	.string "מתמקד בנח והתקפה.$"

BattleDome_Text_EmphasizesHPAndDef::
	.string "מתמקד בנח והגנה.$"

BattleDome_Text_EmphasizesHPAndSpeed::
	.string "מתמקד בנח ומהירות.$"

BattleDome_Text_EmphasizesHPAndSpAtk::
	.string "מתמקד בנח והתקפה מ.$"

BattleDome_Text_EmphasizesHPAndSpDef::
	.string "מתמקד בנח והגנה מ.$"

BattleDome_Text_EmphasizesAtkAndDef::
	.string "מתמקד בהתקפה והגנה.$"

BattleDome_Text_EmphasizesAtkAndSpeed::
	.string "מתמקד בהתקפה ומהירות.$"

BattleDome_Text_EmphasizesAtkAndSpAtk::
	.string "מתמקד בהתקפה והתקפה מ.$"

BattleDome_Text_EmphasizesAtkAndSpDef::
	.string "מתמקד בהתקפה והגנה מ.$"

BattleDome_Text_EmphasizesDefAndSpeed::
	.string "מתמקד בהגנה ומהירות.$"

BattleDome_Text_EmphasizesDefAndSpAtk::
	.string "מתמקד בהגנה והתקפה מ.$"

BattleDome_Text_EmphasizesDefAndSpDef::
	.string "מתמקד בהגנה והגנה מ.$"

BattleDome_Text_EmphasizesSpeedAndSpAtk::
	.string "מתמקד במהירות והתקפה מ.$"

BattleDome_Text_EmphasizesSpeedAndSpDef::
	.string "מתמקד במהירות והגנה מ.$"

BattleDome_Text_EmphasizesSpAtkAndSpDef::
	.string "מתמקד בהתקפה מ. והגנה מ.$"

BattleDome_Text_EmphasizesHP::
	.string "מתמקד בנח.$"

BattleDome_Text_EmphasizesAtk::
	.string "מתמקד בהתקפה.$"

BattleDome_Text_EmphasizesDef::
	.string "מתמקד בהגנה.$"

BattleDome_Text_EmphasizesSpeed::
	.string "מתמקד במהירות.$"

BattleDome_Text_EmphasizesSpAtk::
	.string "מתמקד בהתקפה מ.$"

BattleDome_Text_EmphasizesSpDef::
	.string "מתמקד בהגנה מ.$"

BattleDome_Text_NeglectsHPAndAtk::
	.string "מתעלם מנח והתקפה.$"

BattleDome_Text_NeglectsHPAndDef::
	.string "מתעלם מנח והגנה.$"

BattleDome_Text_NeglectsHPAndSpeed::
	.string "מתעלם מנח ומהירות.$"

BattleDome_Text_NeglectsHPAndSpAtk::
	.string "מתעלם מנח והתקפה מ.$"

BattleDome_Text_NeglectsHPAndSpDef::
	.string "מתעלם מנח והגנה מ.$"

BattleDome_Text_NeglectsAtkAndDef::
	.string "מתעלם מהתקפה והגנה.$"

BattleDome_Text_NeglectsAtkAndSpeed::
	.string "מתעלם מהתקפה ומהירות.$"

BattleDome_Text_NeglectsAtkAndSpAtk::
	.string "מתעלם מהתקפה והתקפה מ.$"

BattleDome_Text_NeglectsAtkAndSpDef::
	.string "מתעלם מהתקפה והגנה מ.$"

BattleDome_Text_NeglectsDefAndSpeed::
	.string "מתעלם מהגנה ומהירות.$"

BattleDome_Text_NeglectsDefAndSpAtk::
	.string "מתעלם מהגנה והתקפה מ.$"

BattleDome_Text_NeglectsDefAndSpDef::
	.string "מתעלם מהגנה והגנה מ.$"

BattleDome_Text_NeglectsSpeedAndSpAtk::
	.string "מתעלם ממהירות והתקפה מ.$"

BattleDome_Text_NeglectsSpeedAndSpDef::
	.string "מתעלם ממהירות והגנה מ.$"

BattleDome_Text_NeglectsSpAtkAndSpDef::
	.string "מתעלם מהתקפה מ. והגנה מ.$"

BattleDome_Text_NeglectsHP::
	.string "מתעלם מנח.$"

BattleDome_Text_NeglectsAtk::
	.string "מתעלם מהתקפה.$"

BattleDome_Text_NeglectsDef::
	.string "מתעלם מהגנה.$"

BattleDome_Text_NeglectsSpeed::
	.string "מתעלם ממהירות.$"

BattleDome_Text_NeglectsSpAtk::
	.string "מתעלם מהתקפה מ.$"

BattleDome_Text_NeglectsSpDef::
	.string "מתעלם מהגנה מ.$"

BattleDome_Text_RaisesMonsWellBalanced::
	.string "מגדל פוקימון בצורה מאוזנת.$"

BattleDome_Text_LetTheBattleBegin::
	.string "שהקרב יתחיל!$"

BattleDome_Text_TrainerWonUsingMove::
	.string "{STR_VAR_1} ניצח תוך שימוש ב{STR_VAR_2}!$"

BattleDome_Text_TrainerBecameChamp::
	.string "{STR_VAR_1} הפך לאלוף!$"

BattleDome_Text_TrainerWonByDefault::
	.string "{STR_VAR_1} ניצח כברירת מחדל!$"

BattleDome_Text_TrainerWonOutrightByDefault::
	.string "{STR_VAR_1} ניצח בצורה מוחלטת כברירת מחדל!$"

BattleDome_Text_TrainerWonNoMoves::
	.string "{STR_VAR_1} ניצח מבלי להשתמש במהלך!$"

BattleDome_Text_TrainerWonOutrightNoMoves::
	.string "{STR_VAR_1} ניצח בצורה מוחלטת בלי להשתמש במהלכים!$"

BattleDome_Text_Round1Match1::
	.string "סיבוב 1, קרב 1$"

BattleDome_Text_Round1Match2::
	.string "סיבוב 1, קרב 2$"

BattleDome_Text_Round1Match3::
	.string "סיבוב 1, קרב 3$"

BattleDome_Text_Round1Match4::
	.string "סיבוב 1, קרב 4$"

BattleDome_Text_Round1Match5::
	.string "סיבוב 1, קרב 5$"

BattleDome_Text_Round1Match6::
	.string "סיבוב 1, קרב 6$"

BattleDome_Text_Round1Match7::
	.string "סיבוב 1, קרב 7$"

BattleDome_Text_Round1Match8::
	.string "סיבוב 1, קרב 8$"

BattleDome_Text_Round2Match1::
	.string "סיבוב 2, קרב 1$"

BattleDome_Text_Round2Match2::
	.string "סיבוב 2, קרב 2$"

BattleDome_Text_Round2Match3::
	.string "סיבוב 2, קרב 3$"

BattleDome_Text_Round2Match4::
	.string "סיבוב 2, קרב 4$"

BattleDome_Text_SemifinalMatch1::
	.string "Semifinal קרב 1$"

BattleDome_Text_SemifinalMatch2::
	.string "Semifinal קרב 2$"

BattleDome_Text_FinalMatch::
	.string "הקרב האחרון$"
