gText_Birch_Welcome::
	.string "הי! סליחה על ההמתנה!\p"
	.string "ברוכים הבאים לעולם הפוקימון!\p"
	.string "שמי הוא בירץ'.\p"
	.string "אבל כולם קוראים לי הפרופסור\n"
	.string "לפוקימון.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "לזה מה שאנחנו קוראים פוקימון.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "העולם שלנו מיושב לרווחה\n"
	.string "ביצורים הידועים בשם פוקימון.\p"
	.string "אנחנו בני האדם חיים לצד פוקימון,\n"
	.string "לעיתים כחברים ידידותיים למשחק,\l"
	.string "לעיתים כעמיתים לעבודה,\p"
	.string "ולעיתים אנחנו נקשרים יחד\n"
	.string "ונלחמים באחרים כמונו. \p"
	.string "אבל למרות הקרבה שלנו, אנחנו לא\n"
	.string "יודעים הכל על פוקימון.\p"
	.string "למעשה, יש הרבה, הרבה\n"
	.string "סודות סביב פוקימון.\p"
	.string "כדי לפענח את תעלומות הפוקימון,\n"
	.string "אני עושה מחקרים.\l"
	.string "זאת פרנסתי.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "ומה איתך?$"

gText_Birch_BoyOrGirl::
	.string "בן?\n"
	.string "או בת?$"

gText_Birch_WhatsYourName::
	.string "מעולה.\n"
	.string "מה שמך?$"

gText_Birch_SoItsPlayer::
	.string "אז את{EMIT_HEY} {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "אה, אוקיי!\p"
	.string "את{EMIT_HEY} {PLAYER}{KUN} שמגיע{ADD_HEY}\n"
	.string "לעיר מולדתי ליטלרוט.\l"
	.string "הבנתי!\p"
	.string "$"

gText_Birch_AreYouReady_Male::
	.string "אוקיי, מוכן?\p"
	.string "ההרפתקה שלך עומדת\n"
	.string "להתחיל.\p"
	.string "אזור אומץ, וזנק אל תוך\n"
	.string "עולם הפוקימון איפה שחלומות,\l"
	.string "הרפתקאות, וחברויות מחכות!\p"
	.string "ובכן, אני מצפה לראותך מאוחר יותר.\n"
	.string "בוא לראות אותי במעבדת הפוקימון שלי.\p"
	.string "$"

gText_Birch_AreYouReady_Female::
	.string "אוקיי, מוכנה?\p"
	.string "ההרפתקה שלך עומדת\n"
	.string "להתחיל.\p"
	.string "אזרי אומץ, וזנקי אל תוך\n"
	.string "עולם הפוקימון איפה שחלומות,\l"
	.string "הרפתקאות, וחברויות מחכות!\p"
	.string "ובכן, אני מצפה לראותך מאוחר יותר.\n"
	.string "בואי לראות אותי במעבדת הפוקימון שלי.\p"
	.string "$"
