BerryBlender_Text_BlendWithTheBlendMaster:
	.string "מאסטר הערבוב: אכן כן!\n"
	.string "אני הוא מאסטר הערבוב!\p"
	.string "ערבב איתי, ותזכה לחזות\n"
	.string "במיומנות שאני מביא לערבוב!$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "מאסטר הערבוב: הממם! אז, ברצונך\n"
	.string "לראות את המיומנות שלי בפעולה?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "המממ!\p"
	.string "אז, את{EMIT_HEY} עסוק{ADD_HEY} מדי עכשיו, אני רואה!\p"
	.string "אך אל חשש!\n"
	.string "אני אהיה כאן כל היום!\l"
	.string "חז{EMIT_VAV}ר{ADD_YUD} מהר מהסידורים שלך!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "המממ!\p"
	.string "אין לך אפילו פרי יער אחד!\p"
	.string "אני אהיה כאן כל היום!\n"
	.string "חז{EMIT_VAV}ר{ADD_YUD} מהר מהסידורים שלך!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "כמובן!\n"
	.string "כמובן!\p"
	.string "דרך אגב…\n"
	.string "את{EMIT_HEY} כן יודע{ADD_TAF} איך לערבב פוקיגושים\l"
	.string "מפירות יער?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "המממ!\p"
	.string "אה, אבל זהו תהליך פשוט!\p"
	.string "כאשר החץ של המערבב מגיע,\n"
	.string "פשוט לח{SWAP_TZADIK}{ADD_YUD} על הכפתור A.\p"
	.string "זה כל מה שעליך לעשות.\p"
	.string "כשתרא{EMIT_HEY}{ADD_YUD} באיזו דייקנות אני לוחץ\n"
	.string "על הכפתור A, את{EMIT_HEY} תבי{SWAP_NUN}{ADD_YUD}.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "בסדר!\p"
	.string "בוא{ADD_YUD} נתחיל, אם כך!\p"
	.string "כולם יחד עם מאסטר הערבוב,\n"
	.string "בואו נערבב פירות יער!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "המממ!\p"
	.string "לא נראה שקיבלת את\n"
	.string "קופסת הפוקיגוש!\p"
	.string "אני אהיה כאן כל היום!\n"
	.string "הש{ADD_YUD}ג{ADD_YUD} את קופסת הפוקיגוש וחז{EMIT_VAV}ר{ADD_YUD} מהר!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "המממ!\p"
	.string "קופסת הפוקיגוש שלא נראית מלאה!\p"
	.string "אני אהיה כאן כל היום!\n"
	.string "השתמש{ADD_YUD} בכמה פוקיגושים וחז{EMIT_VAV}ר{ADD_YUD} מהר!$"

BerryBlender_Text_WhoaAwesome:
	.string "וואה!\n"
	.string "אדיר!$"

BerryBlender_Text_WickedlyFast:
	.string "מהיר בטירוף!$"

BerryBlender_Text_WhatAnExpert:
	.string "איזה מומח{EMIT_HEY}{ADD_YUD}{ADD_TAF}!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "כשאני ערבבתי את המאסטר,\n"
	.string "הכנו פוקיגושים מדהימים!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "עיניים שעוקבות אחר החץ\n"
	.string "בעצימות של מכונה…\p"
	.string "יד שלוחצת על כפתור A\n"
	.string "בדיוק של שעון…\p"
	.string "היכולת להחזיק בתכונות אלו הופכת\n"
	.string "את מאסטר הערבוב לגדול באמת.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "מאסטר הערבוב אמור לעבוד\n"
	.string "על כישוריו עמוק בהרים.\p"
	.string "לפעמים, הוא מגיע לליליקוב\n"
	.string "כדי לערבב פירות יער כל היום.$"
