@ NOTE: The brailleformat macro in this file is leftover from RS.
@       The numbers are simply skipped over. If you'd like to omit
@       this macro you must also stop it from skipping over this
@       section by editing ScrCmd_braillemessage.
Underwater_SealedChamber_Braille_GoUpHere:
	brailleformat 4, 6, 26, 13, 7, 9
	.braille "עלU Kאנ.$" 
	@ עלו כאן

SealedChamber_OuterRoom_Braille_ABC:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "אבVג$"
	@ אבג

SealedChamber_OuterRoom_Braille_GHI:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "זחט$"

SealedChamber_OuterRoom_Braille_MNO:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "מנס$"

SealedChamber_OuterRoom_Braille_TUV:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "קרשץ$"
	@ קרש

SealedChamber_OuterRoom_Braille_DEF:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "דהוOU$"
	@ דהו

SealedChamber_OuterRoom_Braille_JKL:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "יIכKל$"
	@יכל

SealedChamber_OuterRoom_Braille_PQRS:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "סעפFצ$"
	@ סעפצ

SealedChamber_OuterRoom_Braille_Period:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille ".$"

SealedChamber_OuterRoom_Braille_WXYZ:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "ת$"

SealedChamber_OuterRoom_Braille_Comma:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille ",$"

SealedChamber_OuterRoom_Braille_DigHere:
	brailleformat 7, 4, 23, 15, 10, 7
	.braille "חfרU Kאנ.$"
	@ חפרו כאן

SealedChamber_InnerRoom_Braille_FirstWailordLastRelicanth:
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "ראשOנ בא\n"
	.braille "ויילOרד.\n"
	.braille "אחרOנ בא\n"
	.braille "רלIKנת.$"
	@ ראשון בא ויילורד אחרון בא רליקנת

SealedChamber_InnerRoom_Braille_InThisCaveWeHaveLived:
	brailleformat 2, 0, 26, 19, 5, 3
	.braille "במערה הזO\n"
	.braille "חיIנU.$"
	@ במערה הזו חיינו

SealedChamber_InnerRoom_Braille_WeOweAllToThePokemon:
	brailleformat 7, 2, 23, 17, 10, 5
	.braille "אנחנU\n"
	.braille "חייVIמ הKל\n"
	.braille "לפOקIמOנ.$"
	@ אנחנו חייבים הכל לפוקימון

SealedChamber_InnerRoom_Braille_ButWeSealedThePokemonAway:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "אבל אטמנU\n"
	.braille "את הפOקIמOנ.$"
	@ אבל אטמנו את הפוקימון

SealedChamber_InnerRoom_Braille_WeFearedIt:
	brailleformat 5, 6, 25, 13, 8, 9
	.braille "פחדנU ממנO.$"
	@ פחדנו ממנו

SealedChamber_InnerRoom_Braille_ThoseWithCourageHope:
	brailleformat 6, 0, 24, 19, 9, 3
	.braille "בעלי אOמצ,\n"
	.braille "בעלי תקווה.$"
	@ בעלי אומץ, בעלי תקווה.

SealedChamber_InnerRoom_Braille_OpenDoorEternalPokemonWaits:
	brailleformat 3, 2, 27, 17, 6, 5
	.braille "פתחU דלת,\n"
	.braille "פOקIמOנ נצחI\n"
	.braille "מחכה לכמ.$"
	@ פתחו דלת, פוקימון נצחי מחכה לכם.

DesertRuins_Braille_UseRockSmash:
	brailleformat 1, 0, 27, 19, 4, 3
	.braille "ץמאל, ץמאל,\n"
	.braille "למטה, למטה.\n"
	.braille "ואז, השתמשU\n"
	.braille "ברIסUק אVנ.$"
	@ שמאל, שמאל, למטה, למטה. ואז השתמשו בריסוק אבן.

IslandCave_Braille_RunLapAroundWall:
	brailleformat 5, 0, 25, 19, 8, 3
	.braille "הIשארU קרOV\n"
	.braille "לקIר.\n"
	.braille "רUצU סIVUV\n"
	.braille "אחד.$"
	@ הישארו קרוב לקיר, רוצו סיבוב אחד

AncientTomb_Braille_ShineInTheMiddle:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "אלU שיOרשIמ\n"
	.braille "את רצOננU,\n"
	.braille "זOהרIמ\n"
	.braille "באמצע.$"
	@ אלו שיורשים את רצוננו, זוהרים באמצע
