CableClub_Text_WelcomeWhichCableClubService:
	.string "ברו{SWAP_CHAF}{ADD_HEY} הבא{ADD_HEY} למועדון הקישור של פוקימון.\n"
	.string "באיזה שירות תרצ{EMIT_HEY}{ADD_YUD} להשתמש?$"

CableClub_Text_WhichService:
	.string "באיזה שירות תרצ{EMIT_HEY}{ADD_YUD} להשתמש?$"

CableClub_Text_TradeUsingLinkCable::
	.string "החל{SWAP_PEY}{ADD_YUD} פוקימון עם שחקן אחר\n"
	.string "באמצעות כבל קישור של ג.ב.א.$"

CableClub_Text_BattleUsingLinkCable::
	.string "הילח{SWAP_MEM}{ADD_YUD} במאמן אחר\n"
	.string "באמצעות כבל קישור של ג.ב.א.$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "תוכל להשתמש בפינת הרשומות\n"
	.string "יחד עם אחרים באמצעות כבל קישור של ג.ב.א.$"

CableClub_Text_CloseThisMenu:
	.string "סג{EMIT_VAV}ר{ADD_YUD} את התפריט הזה.$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "כדי להשתתף בקרב זוגי, עליך\n"
	.string "להחזיק לפחות שני פוקימונים.$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "כדי לבצע החלפה, עליך\n"
	.string "להחזיק לפחות שני פוקימונים.$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "לא ניתן להחליף פוקימון שמחזיק\n"
	.string "בפרי {STR_VAR_1}.$"

gText_PleaseWaitForLink::
	.string "אנא המת{SWAP_NUN}{ADD_YUD}.\n"
	.string "… … כפתור B: ביטול$"

gText_ConfirmLinkWhenPlayersReady::
	.string "כאשר כל השחקנים מוכנים…\n"
	.string "כפתור A: אישור\l"
	.string "כפתור B: ביטול$"

gText_ConfirmStartLinkWithXPlayers::
	.string "התח{ADD_YUD}ל{ADD_YUD} קישור עם {STR_VAR_1} שחקנים.\n"
	.string "כפתור A: אישור\l"
	.string "כפתור B: ביטול$"

gText_AwaitingLinkup::
	.string "ממתין לחיבור…\n"
	.string "… … כפתור B: ביטול$"

CableClub_Text_OkayToSaveProgress::
	.string "יש לשמור את ההתקדמות לפני הקישור.\n"
	.string "האם לשמור כעת?$"

CableClub_Text_PleaseEnter:
	.string "אנא היכנס{ADD_YUD}.$"

CableClub_Text_DirectYouToYourRoom:
	.string "אכוון אותך כעת לחדרך.$"

Text_SomeoneIsNotReadyToLink:
	.string "מישהו מהשחקנים עדיין לא מוכן.\p"
	.string "אנא חזרו לאחר שכל המשתתפים\n"
	.string "סיימו את ההכנות.$"

Text_LinkErrorPleaseReset:
	.string "מצטערים, אירעה שגיאת קישור…\n"
	.string "אנא אפס{ADD_YUD} ונס{EMIT_HEY}{ADD_YUD} שוב.$"

Text_PlayersMadeDifferentSelections:
	.string "נראה כי השחקנים ביצעו\n"
	.string "בחירות שונות.$"

CableClub_Text_PleaseVisitAgain:
	.string "נשמח לראותך שוב.$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "מספר המשתתפים שגוי.$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "מצב קרב יחיד לא ניתן לביצוע עם\n"
	.string "{STR_VAR_1} שחקנים.$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "מצב קרב זוגי לא ניתן לביצוע עם\n"
	.string "{STR_VAR_1} שחקנים.$"

CableClub_Text_NeedFourPlayers:
	.string "נדרשים ארבעה שחקנים כדי לשחק\n"
	.string "במצב קרב זה.$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "אנא ודאו את מספר השחקנים\n"
	.string "והתחילו שוב.$"

Text_TerminateLinkConfirmation:
	.string "אם תעז{EMIT_VAV}ב{ADD_YUD} את החדר, הקישור יסתיים.\n"
	.string "האם זה בסדר?$"

Text_TerminateLinkPleaseWait:
	.string "מסיים את הקישור…\n"
	.string "תועבר{ADD_YUD} מחוץ לחדר.\l"
	.string "אנא המת{SWAP_NUN}{ADD_YUD}.$"

CableClub_Text_TooBusyToNotice:
	.string "המאמן הזה עסוק מכדי לשים לב…$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "מעולה! הצלחת לראות את כרטיס\n"
	.string "המאמן של {STR_VAR_1}!$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "מעולה! הצלחת לראות את כרטיס\n"
	.string "המאמן של {STR_VAR_1}!\p"
	.string "זה כרטיס {STR_VAR_2}!$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "קחו את מקומכם והתחילו\n"
	.string "את הקרב שלכם.$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "שבו במקומכם והתחילו את ההחלפה.$"

RecordCorner_Text_ThanksForComing:
	.string "תודה שבאת.$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "נתוני כרטיס המאמן שלך\n"
	.string "יוחלפו בנתונים חדשים.$"

CableClub_Text_HopeToSeeYouAgain:
	.string "מקווים לראותך שוב!$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "אנו מצטערים מאוד.\p"
	.string "לא ניתן כעת לבצע החלפות עם מאמנים\n"
	.string "שנמצאים באזור רחוק.$"

CableClub_Text_OtherTrainerNotReady:
	.string "המאמן השני עדיין לא מוכן.$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "ברשותך לפחות פוקימון אחד\n"
	.string "שלא ניתן להביא.$"

RecordCorner_Text_TakeSeatAndWait:
	.string "שב{ADD_YUD} במקומך והמת{SWAP_NUN}{ADD_YUD}.$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{STR_VAR_1} שלח אליך\n"
	.string "פוקימון מסוג {STR_VAR_2}.$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "מצטערים, אירעה שגיאת תקשורת.\p"
	.string "לא ניתן לערבב רשומות עם גרסאות\n"
	.string "יפניות של רובי או ספיר.\p"
	.string "כמו כן, לא ניתן לערבב רשומות בין\n"
	.string "ברקת יפנית וגרסאות זרות של רובי או ספיר.$"

CableClub_Text_AdapterNotConnected:
	.string "מתאם האלחוטי אינו מחובר כראוי.$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "אנא גשו אל דלפק הקבלה, משתתפים יקרים.$"

CableClub_Text_Hello:
	.string "שלום!$"

CableClub_Text_PleaseWait:
	.string "אנא המת{SWAP_NUN}{ADD_YUD}.$"

CableClub_Text_YouMayTradeHere::
	.string "כאן ניתן להחליף פוקימון עם מאמן אחר.$"

CableClub_Text_YouMayBattleHere::
	.string "כאן ניתן להילחם עם חבריך.$"

CableClub_Text_CanMakeBerryPowder::
	.string "שניים עד חמישה מאמנים יכולים להכין\n"
	.string "אבקת פירות יער יחד.$"

CableClub_Text_CanMixRecords::
	.string "הרשומות של שניים עד ארבעה שחקנים\n"
	.string "יכולות להתמזג יחד.$"

CableClub_Text_GuideToVariousServices:
	.string "מדריך לשירותים השונים של מועדון האלחוטי.$"

CableClub_Text_CancelSelectedItem::
	.string "ביטול הפריט שנבחר בתפריט.$"

CableClub_Text_WhichBattleMode:
	.string "באיזה מצב קרב תרצ{EMIT_HEY}{ADD_YUD} לשחק?$"

CableClub_Text_ReturnsToPreviousStep:
	.string "חוזר לשלב הקודם.$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "כדי להשתמש בשירות ריסוק הפירות יער,\n"
	.string "עליך להחזיק לפחות פרי אחד.$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "כדי להיכנס לחדר האיחוד, עליך\n"
	.string "להחזיק לפחות שני פוקימונים.$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "לא ניתן להיכנס לחדר האיחוד עם\n"
	.string "פוקימון שמחזיק בפרי {STR_VAR_1}.$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "זהו חדר האיחוד של מועדון הפוקימון האלחוטי.\p"
	.string "לצערנו, מתאם האלחוטי שלך אינו\n"
	.string "מחובר כראוי.\p"
	.string "נשמח לראותך שוב.$"

CableClub_Text_OhExcuseMe:
	.string "אה…\n"
	.string "סליחה!$"

CableClub_Text_PlayerIsWaiting:
	.string "נראה כי {STR_VAR_1} משחק כרגע.\l"
	.string "בהצלחה!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "אני יכול להסביר לך את חוקי המשחק,\n"
	.string "אם תרצ{EMIT_HEY}{ADD_YUD}.\p"
	.string "איזה משחק תרצ{EMIT_HEY}{ADD_YUD} שאסביר?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "“קפיצת פוקימון”\p"
	.string "גרום לפוקימון שלך לדלג מעל חבל השוט\n"
	.string "גפן עם הכפתור A.\p"
	.string "רק פוקימונים קטנים מתחת ל-7.0מ\n"
	.string "יכולים להשתתף.\p"
	.string "פוקימון שיכול רק לשחות, לחפור,\n"
	.string "או לעוף, אינו טוב בקפיצה.\p"
	.string "כתוצאה מכך, הוא לא יוכל להשתתף.\p"
	.string "דברים טובים קורים אם כולם קופצים בזמן.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "“קטיפת פרי יער עם דודריו”\p"
	.string "של{EMIT_VAV}ט{ADD_YUD} בשלושת הראשים של דודריו\n"
	.string "כדי לתפוס את הפירות יער הנופלים.\p"
	.string "לח{SWAP_TZADIK}{ADD_YUD} ימינה, למעלה או שמאלה בכפתורי\n"
	.string "על ה{PLUS} כדי להזיז את הראשים.\p"
	.string "כדי לשחק במשחק הזה, עליך להחזיק בדודריו.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "אם ברצונך לשחק משחק,\n"
	.string "אנא דבר{ADD_YUD} עם האיש הזקן שלידי.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "שלום, ברו{SWAP_CHAF}{ADD_HEY} הבא{ADD_HEY}!\n"
	.string "האם הגעת לשחק משחקים באמצעות\n"
	.string "תקשורת אלחוטית?\p"
	.string "האם תוכל{ADD_YUD} להמתין קצת?$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "בסדר, נשמח לראותך שוב!$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "מתאם האלחוטי אינו מחובר.\n"
	.string "חז{EMIT_VAV}ר{ADD_YUD} כאשר הוא מחובר כראוי!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "אז איזה משחק תרצ{EMIT_HEY}{ADD_YUD} לשחק?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "איזה פוקימון תרצ{EMIT_VAV}{ADD_YUD} להכניס?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "הכל מוכ{SWAP_NUN}{ADD_HEY}, את{EMIT_HEY} מוכן להתחיל.\n"
	.string "אל תית{SWAP_NUN}{ADD_YUD} לאחרים לנצח אותך!$"

MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "האם את{EMIT_HEY} עוזב{ADD_TAF} עכשיו?\n"
	.string "נשמח לראותך שוב!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "נראה שאין לך פוקימון שניתן להכניס…\p"
	.string "האם תרצ{EMIT_HEY}{ADD_YUD} שאסביר אילו פוקימון\n"
	.string "ניתן להכניס?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "“קפיצת פוקימון” פתוח לפוקימון מתחת\n"
	.string "ל-7.0מ או פחות.\p"
	.string "פוקימון שלא יכול לקפוץ אינו יכול להיכנס.\p"
	.string "כמו פוקימון שיכול רק לשחות, לחפור\n"
	.string "או לעוף.\p"
	.string "זה כל מה שאת{EMIT_HEY} צרי{SWAP_CHAF}{ADD_HEY} לדעת.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "קטיפת פרי יער עם דודריו הוא משחק שבו\n"
	.string "יכולים להשתתף רק עם דודריו.$"

MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "האם תוכל{ADD_YUD} לנסות שוב מההתחלה, בבקשה?$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "ברו{SWAP_CHAF}{ADD_HEY} הבא{ADD_HEY} לפינת ההחלפות הישירה\n"
	.string "של מועדון הפוקימון האלחוטי.\p"
	.string "כאן תוכל{ADD_YUD} לתקשר ישירות עם\n"
	.string "חבריך.\p"
	.string "איזה חדר תרצ{EMIT_HEY}{ADD_YUD} להיכנס?$"

CableClub_Text_TradePokemon:
	.string "האם תרצ{EMIT_HEY}{ADD_YUD} להחליף פוקימון?$"

CableClub_Text_PlayWhichBattleMode:
	.string "באיזה מצב קרב תרצ{EMIT_HEY}{ADD_YUD} לשחק?$"

CableClub_Text_AccessRecordCorner:
	.string "האם תרצ{EMIT_HEY}{ADD_YUD} לגשת לפינת הרשומות?$"

CableClub_Text_UseBerryCrush:
	.string "האם תרצ{EMIT_HEY}{ADD_YUD} להשתמש במערכת ריסוק הפירות?$"

CableClub_Text_ExplainBattleModes:
	.string "יש שלושה מצבי קרב.\p"
	.string "קרב יחיד מתאים לשני מאמנים\n"
	.string "עם פוקימון אחד או יותר לכל אחד.\p"
	.string "כל מאמן יכול להכניס פוקימון אחד\n"
	.string "לקרב בכל פעם.\p"
	.string "קרב זוגי מתאים לשני מאמנים\n"
	.string "עם שני פוקימונים או יותר לכל אחד.\p"
	.string "כל מאמן ישלח שני פוקימונים לקרב בכל פעם.\p"
	.string "קרב קבוצתי מתאים לארבעה מאמנים\n"
	.string "עם פוקימון אחד או יותר לכל אחד.\p"
	.string "כל מאמן יכול להכניס פוקימון אחד\n"
	.string "לקרב בכל פעם.$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "בחרו מי מכם יהיה המנהיג.\p"
	.string "השחקן השני צריך לבחור\n"
	.string "“הצטרף לקבוצה.”$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "בחרו מי מכם יהיה מנהיג הקבוצה.\p"
	.string "שאר השחקנים צריכים לבחור\n"
	.string "“הצטרף לקבוצה.”$"

CableClub_Text_ChooseGroupLeader:
	.string "בחרו מי יהיה מנהיג הקבוצה.\p"
	.string "שאר השחקנים צריכים לבחור\n"
	.string "“הצטרף לקבוצה.”$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "ברו{SWAP_CHAF}{ADD_HEY} הבא{ADD_HEY} לחדר האיחוד של מועדון\n"
	.string "הפוקימון האלחוטי.\p"
	.string "כאן תוכל{ADD_YUD} לתקשר ישירות עם\n"
	.string "מאמנים אחרים, חלקם אולי לא תכיר{ADD_YUD}.\p"
	.string "האם תרצ{EMIT_HEY}{ADD_YUD} להיכנס לחדר?$"

CableClub_Text_UnionRoomInfo:
	.string "המאמנים בחדר האיחוד יהיו השחקנים\n"
	.string "שמסביבך והיכנסו גם הם לחדר.\p"
	.string "כאן ניתן לבצע פעולות רבות,\n"
	.string "כמו החלפת ברכות.\p"
	.string "ניתן להכניס שני פוקימונים עד\n"
	.string "רמה 03 לקרב אחד על אחד.\p"
	.string "ניתן להשתתף בשיחה עם\n"
	.string "שניים עד חמישה משתתפים.\p"
	.string "או ניתן לרשום פוקימון למסחר.\p"
	.string "האם תרצה להיכנס לחדר?$"

CableClub_Text_EnjoyUnionRoom:
	.string "אני מקווה שתיהנ{EMIT_HEY}{ADD_YUD} בזמן שלך\n"
	.string "בחדר האיחוד.$"

CableClub_Text_FirstTimeRightThisWay:
	.string "שלום!\n"
	.string "שמי תהילה.\p"
	.string "זו כנראה הפעם הראשונה שלך כאן.\p"
	.string "אני אראה לך כיצד פועל\n"
	.string "מערכת התקשורת האלחוטית.\p"
	.string "קודם כל, אני צריך להראות לך\n"
	.string "את הקומה הזו של מרכז הפוקימון שלנו.\p"
	.string "לכאן, בבקשה.$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "בקומה העליונה יש שני חדרים.\p"
	.string "קודם, החדר משמאל.\n"
	.string "זהו חדר האיחוד.\p"
	.string "תוכל{ADD_YUD} לתקשר עם מאמנים סביבך\n"
	.string "שגם הם נכנסו לחדר האיחוד.\p"
	.string "איתם, ניתן לבצע פעולות כמו\n"
	.string "שיחה, קרב והחלפות.\p"
	.string "השני, החדר מימין הוא פינת ההחלפות הישירה.\p"
	.string "כאן ניתן להחליף או להילחם עם חבריך.\p"
	.string "אם מתאם האלחוטי אינו מחובר,\n"
	.string "תוכל עדיין להשתמש בכבל קישור של ג.ב.א.\p"
	.string "במקרה כזה, יש לגשת לפינת ההחלפות הישירה.\p"
	.string "אני מקווה שתיהנ{EMIT_HEY}{ADD_YUD} מהמערכת האלחוטית.$"

CableClub_Text_AskAboutLinking:
	.string "שלום, {PLAYER}!\p"
	.string "אני תהילה, הפקידה בקומה 2 של מרכז הפוקימון.\p"
	.string "יש משהו שתרצ{EMIT_HEY}{ADD_YUD} לשאול על קישור?$"

CableClub_Text_ExplainWirelessClub:
	.string "הרש{EMIT_HEY}{ADD_YUD} לי להסביר כיצד פועל מועדון הפוקימון האלחוטי.\p"
	.string "בקומה העליונה יש שני חדרים.\p"
	.string "קודם, החדר משמאל הוא חדר האיחוד.\p"
	.string "תוכל{ADD_YUD} לתקשר עם מאמנים סביבך\n"
	.string "שגם הם נכנסו לחדר האיחוד.\p"
	.string "איתם, ניתן לבצע פעולות כמו\n"
	.string "שיחה, קרב והחלפות.\p"
	.string "השני, החדר מימין הוא פינת ההחלפות הישירה.\p"
	.string "כאן ניתן להחליף או להילחם עם חבריך.\p"
	.string "לפעמים, לא תמצא{ADD_YUD} את חבריך בחדר האיחוד\n"
	.string "או בפינת ההחלפות הישירה.\p"
	.string "במקרה כזה, התקרב{ADD_YUD} אליהם.\p"
	.string "אם מתאם האלחוטי אינו מחובר,\n"
	.string "תוכל עדיין להשתמש בכבל קישור של ג.ב.א.\p"
	.string "במקרה כזה, יש לגשת לפינת ההחלפות הישירה.\p"
	.string "אני מקווה שתיהנ{EMIT_HEY}{ADD_YUD} מהמערכת האלחוטית.$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "אני מקווה שתהנ{EMIT_HEY}{ADD_YUD} מהמערכת האלחוטית.$"
