Text_PictureBookShelf:
	.string "יש סט של ספרי תמונות של פוקימון.$"

Text_BookShelf:
	.string "מלא בכל מיני ספרים.$"

Text_PokemonCenterBookShelf:
	.string "מגזיני פוקימון!\n"
	.string "חבר פוקימון…\p"
	.string "מדריך לפוקימון…\n"
	.string "פוקימון חמוד…$"

Text_Vase:
	.string "האגרטל הזה נראה יקר…\n"
	.string "הצצתי פנימה…\p"
	.string "אבל, זה ריק.$"

Text_EmptyTrashCan:
	.string "זה ריק.$"

Text_ShopShelf:
	.string "המדפים עמוסים בכל מיני\n"
	.string "מוצרי פוקימון.$"

Text_Blueprint:
	.string "תוכנית כלשהי?\n"
	.string "זה מסובך מדי!$"
