@ With the exception of Link standby, none of the below texts are used

gTest_MissedTurn::
	.string "תור הוחמץ$"

gText_LinkStandby4::
	.string "המתנה לקשר!$"

gText_WinnerIsPlayersMonCongrats::
	.string "המנצח הוא {STR_VAR_2} של {STR_VAR_1}!\n"
	.string "ברכות!$"

gText_WinnerIsPlayersMon::
	.string "המנצח הוא {STR_VAR_2} של {STR_VAR_1}!{PAUSE_UNTIL_PRESS}$"

gText_PrimaryJudgingNumX::
	.string "שיפוט ראשוני: מס' {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SecondaryJudgingNumX::
	.string "שיפוט משני: מס' {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX::
	.string "אירוע: מס' {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MoveUsedMostOften::
	.string "המהלך שהשתמשו בו הכי הרבה:\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MostImpressiveMon::
	.string "הפוקימון המרשים ביותר:\n"
	.string "{STR_VAR_2} של {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX2::
	.string "אירוע: מס' {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
	.string "תוכנית הטלוויזיה בקשר לא תופק\n"
	.string "בגלל שהמאמן הפסיד.{PAUSE_UNTIL_PRESS}$"
