gContestHallPaintingCaption::
	.string "{STR_VAR_1}\n"
	.string "{STR_VAR_3} של {STR_VAR_2}$"

@ Unused
gContestPaintingContest::
	.string "תחרות$"

gContestRankNormal::
	.string "דירוג רגיל$"

gContestRankSuper::
	.string "דירוג סופר$"

gContestRankHyper::
	.string "דירוג הייפר$"

gContestRankMaster::
	.string "דירוג מאסטר$"

gContestLink::
	.string "קשר$"

gContestCoolness::
	.string "מגניבות$"

gContestBeauty::
	.string "יופי$"

gContestCuteness::
	.string "חמידות$"

gContestSmartness::
	.string "חוכמה$"

gContestToughness::
	.string "קשיחות$"

gContestPaintingCool1::
	.string "מגניב ללא הפסקה--\n"
	.string "{STR_VAR_1} הבלתי נמדד$"

gContestPaintingCool2::
	.string "היי שם!\n"
	.string "הפוקימון הנאה {STR_VAR_1}$"

gContestPaintingCool3::
	.string "{STR_VAR_1} המופלא, הנהדר,\n"
	.string "והמאוד גדול$"

gContestPaintingBeauty1::
	.string "ונוס האחרונה של המאה הזו--\n"
	.string "{STR_VAR_1} היפהפה$"

gContestPaintingBeauty2::
	.string "החיוך הזוהר והנוצץ\n"
	.string "של {STR_VAR_1}$"

gContestPaintingBeauty3::
	.string "הדמות הנערצת של מרכז הפוקימון--\n"
	.string "{STR_VAR_1} הבלתי ניתן להשוואה$"

gContestPaintingCute1::
	.string "{STR_VAR_1} המתוק והחמוד$"

gContestPaintingCute2::
	.string "הדיוקן המנצח של\n"
	.string "{STR_VAR_1} החמוד$"

gContestPaintingCute3::
	.string "תקרוץ לנו!\n"
	.string "הפוקימון החמוד {STR_VAR_1}$"

gContestPaintingSmart1::
	.string "מאסטר החוכמה--\n"
	.string "הפוקימון החכם {STR_VAR_1}$"

gContestPaintingSmart2::
	.string "{STR_VAR_1}--הנבחר\n"
	.string "מעל כל הפוקימונים$"

gContestPaintingSmart3::
	.string "הרגע האלגנטי של\n"
	.string "{STR_VAR_1} המעולה$"

gContestPaintingTough1::
	.string "{STR_VAR_1} המהיר והשרירי\n"
	.string "בעוצמה$"

gContestPaintingTough2::
	.string "החזק, החזק יותר, והכי\n"
	.string "חזק {STR_VAR_1}$"

gContestPaintingTough3::
	.string "הקשוח העוצמי\n"
	.string "פוקימון העל {STR_VAR_1}$"
