EventTicket_Text_ShowOldSeaMap:
	.string "המעבורת לסלייטפורט היא…\p"
	.string "סליחה?\n"
	.string "האם נוכל להפליג למקום הזה על המפה?\p"
	.string "אני מכיר מישהו שיעזור לך טוב יותר.\n"
	.string "בבקשה תחכ{EMIT_HEY}{ADD_YUD}.$"

EventTicket_Text_ThatPass:
	.string "המעבורת לסלייטפורט היא…\p"
	.string "או?\n"
	.string "ההיתר הזה…$"

EventTicket_Text_ShowEonTicket:
	.string "איי, חבר{ADD_HEY}, את{EMIT_HEY} שהבאת אתt\n"
	.string "ההיתר המוזר והאדיר הזה?\p"
	.string "אני אגיד לך, את{EMIT_HEY} מנסה להגיע\n"
	.string "לאי קטנטן הרחק בדרום.\p"
	.string "אי אפשר לדעת במה ניתקל\n"
	.string "כשנגיע לשם, איי.\l"
	.string "זה מרעיד לי את הקורות!\p"
	.string "כולם לעלות!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "איי, חבר{ADD_HEY}, אין כאם שום דבר לראות\n"
	.string "או לעשות באי הנשכח הזה.\p"
	.string "מה דעתך שנפליג בחזרה לליליקוב?$"

EventTicket_Text_SailHome:
	.string "איי, בסדר, אם כן!\n"
	.string "נפליג הביתה!$"

EventTicket_Text_AsYouLike:
	.string "איי, בסדר, כרצונך, אם כן.$"

SouthernIsland_Interior_Text_Sign:
	.string "”כל החלומות אינם אלא מציאות אחרת.\n"
	.string "לעולם אל תשכח{ADD_YUD}…“$"

SouthernIsland_Exterior_Text_Sign:
	.string "”אלו שזיכרונותיהם דוהים מבקשים\n"
	.string "לחרוט אותם בליבם…“$"
