EventTicket_Text_OldSeaMapTooFar:
	.string "מה נשמע, צעיר{ADD_HEY}?\p"
	.string "מה, זה את{EMIT_HEY} שאמור{ADD_HEY} להחזיק\n"
	.string "מפה ישנה ובלויה?\p"
	.string "בוא{ADD_YUD} נראה.\n"
	.string "… … … … … …\p"
	.string "וואי,זה ממש רחוק מכאן.\n"
	.string "אני חושש שאני לא אוכל לעזור לך…$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "ברייני: חכ{EMIT_HEY}{ADD_YUD} רגע!\p"
	.string "מה הרעיון בלסרב למישה{EMIT_VAV}{ADD_YUD}\n"
	.string "שאני חייב ל{EMIT_VAV}{ADD_HEY} כל כך הרבה?$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}{KUN}, אני נורא מצטער.\p"
	.string "באת אליי כדי לבקש את עזרתי,\n"
	.string "וכמעט שסירבנו לך.\p"
	.string "ובכן, ת{SWAP_NUN}{ADD_YUD} לי לתקן את זה.\p"
	.string "נפליג מיד, כמובן!\p"
	.string "בוא{ADD_YUD} נמצא את האי הזה בעזרת\n"
	.string "מפת הים הישנה הזו!$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "את{EMIT_HEY} מי שהביא{ADD_HEY} את הכרטיס\n"
	.string "המשונה הזה?\p"
	.string "לאן שאת{EMIT_HEY} מנסה להגיע הוא אי\n"
	.string "רחוק, רחוק מאוד.\p"
	.string "אף אחד לא יודע מה מחכה שם…\p"
	.string "עצם המחשבה על זה מרגשת את דמי\n"
	.string "כמפליג ותיק!\p"
	.string "על{EMIT_HEY}{ADD_YUD} על הסיפון, צעיר{ADD_HEY}!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "קפטן ברייני יכול להיות כל כך\n"
	.string "בלתי צפוי לפעמים…\p"
	.string "האם תרצ{EMIT_HEY}{ADD_YUD} לחזור לליליקוב?$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "איזה אי מוזר בצורתו, אה?\n"
	.string "האם תרצ{EMIT_HEY}{ADD_YUD} לחזור לליליקוב?$"

EventTicket_Text_OddTicketsWhereTo:
	.string "האם זה את{EMIT_HEY} שהביא{ADD_HEY} את הכרטיסים\n"
	.string "המשונים האלו?\p"
	.string "… … …המ.\p"
	.string "הכרטיסים האלו יביאו אותך לאיים\n"
	.string "רחוקים, רחוקים מאוד.\p"
	.string "אף אחד לא יודע מה מחכה שם,\n"
	.string "או מה עשוי לקרות שם.\p"
	.string "עצם המחשבה על זה מרגשת את דמי\n"
	.string "כמפליג ותיק!\p"
	.string "על{EMIT_HEY}{ADD_YUD} על הסיפון, צעיר{ADD_HEY}!\n"
	.string "לאן נפליג תחילה?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "האם… האם שמעת את זה?\n"
	.string "הנהמה הנמוכה משם, מעומק המקום.\p"
	.string "האם את{EMIT_HEY} בטוח{ADD_HEY} שזה בטוח?\n"
	.string "את{EMIT_HEY} חושב{ADD_HEY} שכדאי שנעזוב?$"

FarawayIsland_Entrance_Text_Sign:
	.string "הכיתוב דהוי כאילו נכתב \n"
	.string "לפני הרבה מאוד זמן…\p"
	.string "”שישי באוק…\n"
	.string "אם כל אדם…ידרוך כאן…\l"
	.string "שוב…יה אדם טוב לב…\l"
	.string "…עם תקווה זו, אני עוז…“$"

FarawayIsland_Interior_Text_Mew:
	.string "מיוו…$"
