@ Battle Tower
gText_AnabelWonSilver::
	.string "זה מאוד מאכזב…$"

gText_AnabelDefeatSilver::
	.string "אוקיי, אני מבינה…$"

gText_AnabelWonGold::
	.string "אני מאוד מצטערת…$"

gText_AnabelDefeatGold::
	.string "תודה לך…$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "אהאהאהא! את{EMIT_HEY} לא מוב{SWAP_CHAF}{ADD_TAF}?\n"
	.string "כולם צופים!$"

gText_TuckerDefeatSilver::
	.string "גרר…\n"
	.string "מה לע…$"

gText_TuckerWonGold::
	.string "התואר אלוף הכיפה הוא לא רק בשביל היופי!$"

gText_TuckerDefeatGold::
	.string "אהאהאהא!\n"
	.string "את{EMIT_HEY} נות{SWAP_NUN}{ADD_TAF} השראה!$"

@ Battle Factory
gText_NolandWonSilver::
	.string "עבדת יפה!\n"
	.string "זה היה שיעור טוב, הא?$"

gText_NolandDefeatSilver::
	.string "עבודה טובה!\n"
	.string "את{EMIT_HEY} יודע{ADD_TAF} מה את{EMIT_HEY} עושה!$"

gText_NolandWonGold::
	.string "היי, היי, היי!\n"
	.string "כבר סיימת?$"

gText_NolandDefeatGold::
	.string "מה קרה כאן?$"

@ Battle Pike
gText_LucyWonSilver::
	.string "המף…$"

gText_LucyDefeatSilver::
	.string "אוך…$"

gText_LucyWonGold::
	.string "הא!$"

gText_LucyDefeatGold::
	.string "לעזאזל!$"

@ Battle Arena
gText_GretaWonSilver::
	.string "או, בחייאת!\n"
	.string "את{EMIT_HEY} חייב{ADD_TAF} להתאמץ יותר מזה!$"

gText_GretaDefeatSilver::
	.string "אין מצב!\n"
	.string "עבודה טובה!$"

gText_GretaWonGold::
	.string "חהחהחה!\n"
	.string "מה ציפית?$"

gText_GretaDefeatGold::
	.string "הא?\n"
	.string "את{EMIT_HEY} רציני{ADD_TAF}?!$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "הפוקימונים שלך חלשים כי\n"
	.string "את{EMIT_HEY} חלש{ADD_HEY} כמאמ{SWAP_NUN}{ADD_TAF}!$"

gText_SpenserDefeatSilver::
	.string "אה…\n"
	.string "עכשיו זה משהו אחר…$"

gText_SpenserWonGold::
	.string "גוואהאהאהא!\n"
	.string "אחיי, אין לנו ממה לפחד!$"

gText_SpenserDefeatGold::
	.string "גוואה!\n"
	.string "האהאהאהא!$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "היי! מה לא בסדר איתך!\n"
	.string "בוא{ADD_YUD} נראה קצת מאמץ! תקו{SWAP_MEM}{ADD_YUD}!$"

gText_BrandonDefeatSilver::
	.string זהו זה! היית נהדר{ADD_TAF}!\n"
	.string "עבדת קשה בשביל זה!$"

gText_BrandonWonGold::
	.string "היי! אל תוותר{ADD_YUD} עכשיו!\n"
	.string "קו{SWAP_MEM}{ADD_YUD}! אל תאבד{ADD_YUD} אמונה בעצמך!$"

gText_BrandonDefeatGold::
	.string "זהו זה! עשית את זה!\n"
	.string "המשכת לעבוד בשביל זה!$"
