@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string " כל כך יפה!$"

GiddyText_SoDarling::
	.string " כל כך חמוד!$"

GiddyText_SoRelaxed::
	.string " כל כך רגוע!$"

GiddyText_SoSunny::
	.string " כל כך שטוף שמש!$"

GiddyText_SoDesirable::
	.string " כל כך נחשק!$"

GiddyText_SoExciting::
	.string " כל כך מרגש!$"

GiddyText_SoAmusing::
	.string " כל כך משעשע!$"

GiddyText_SoMagical::
	.string " כל כך קסום!$"

GiddyText_Is::
	.string " הוא$"

GiddyText_DontYouAgree::
	.string "\n"
	.string "את{EMIT_HEY} לא מסכי{SWAP_MEM}{ADD_HEY}?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "אני כל כך רוצה לצאת לחופשה.\n"
	.string "במקרה יצא לך להכיר מקום נחמד?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "קניתי עפרונות צבעוניים עם 021 צבעים!\n"
	.string "את{EMIT_HEY} לא חושב{ADD_TAF} שזה נחמד?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "זה היה לא נחמד אם יכולנו לרחף\n"
	.string "בשמיים על ענן של בועות?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "כשאת{EMIT_HEY} כותב{ADD_TAF} על חוף חולי,\n"
	.string "זה נשטף. זה מעציב אותי.$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "איך נראית קרקעית הים?\n"
	.string "הייתי כל כך רוצה להגיע לשם פעם אחת!$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "כשאת{EMIT_HEY} רואה את השמש שוקעת, זה\n"
	.string "גורם לך לרצות ללכת הביתה?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "לשכב אחורה על הדשא הירוק…\n"
	.string "או, זה כל כך, כל כך נחמד!$"

GiddyText_SecretBasesAreSoWonderful::
	.string "בסיסים סודיים הם כל כך נפלאיים!\n"
	.string "את{EMIT_HEY} לא מרגיש{ADD_HEY} את ההתרגשות?$"
