MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "המהלך הזה יכול להילמד\n"
	.string "רק פעם אחת. האם זה בסדר?$"

MoveTutor_Text_SwaggerTeach:
	.string "חה! הפוקימון שלי פשוט מדהים!\n"
	.string "הוא מגניב יותר מכל פוקימון!\p"
	.string "הלכתי עם יהירות כזו\n"
	.string "וכשניצבתי מול הנשיא\l"
	.string "הוא כעס עלי.\p"
	.string "זה הוציא ממני את כל היהירות.\p"
	.string "אם תרצה, אלמד את המהלך\n"
	.string "יהירות לפוקימון שלך.$"

MoveTutor_Text_SwaggerDeclined:
	.string "מה, לא? לא בא לך להשתתף\n"
	.string "ברוח הדברים?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "טוב, איזה פוקימון רוצה\n"
	.string "ללמוד יהירות?$"

MoveTutor_Text_SwaggerTaught:
	.string "מעתה אני אסתפק בשבחים לפוקימון\n"
	.string "בלי יהירות.$"

MoveTutor_Text_RolloutTeach:
	.string "הידעת שניתן להמשיך מכאן\n"
	.string "הרחק באותו הכיוון\l"
	.string "בלי לשנות כיוון?\p"
	.string "אני אפילו מסוגל להתגלגל\n"
	.string "באותו האופן.\p"
	.string "האם נראה לך שפוקימון שלך\n"
	.string "גם ירצה להתגלגל?\p"
	.string "אם תרצ{EMIT_HEY}{ADD_YUD}, אני אוכל ללמד את\n"
	.string "המהלך גלגול.$"

MoveTutor_Text_RolloutDeclined:
	.string "את{EMIT_HEY} לא צרי{SWAP_CHAF}{ADD_HEY} להתבייש לגבי זה.\n"
	.string "בוא{ADD_YUD} נתגלגל!$"

MoveTutor_Text_RolloutWhichMon:
	.string "אהה, בטח! זה יהיה נהדר\n"
	.string "אם הפוקימון ייראה כמוני.$"

MoveTutor_Text_RolloutTaught:
	.string "להתגלגל בדשא משמח אותי.\n"
	.string "קדימה, בוא{ADD_YUD} נתגלגל!$"

MoveTutor_Text_FuryCutterTeach:
	.string "קיים מהלך שמתחזק\n"
	.string "כשמשתמשים בו ברצף.\p"
	.string "זה מהלך מסוג חרק והוא\n"
	.string "מאוד מגניב.\p"
	.string "שמו הוא חיתוך זעם.\n"
	.string "רוצה שאלמד אותו לפוקימון?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "אנחנו לא באותו תדר.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "יאי!\n"
	.string "הרא{EMIT_HEY}{ADD_YUD} לי איזה פוקימון עלי ללמד.$"

MoveTutor_Text_FuryCutterTaught:
	.string "זה מרגש אותי לראות אם\n"
	.string "המהלך ימשיך לפגוע ברצף!$"

MoveTutor_MimicTeach:
	.string "אה, צעיר{ADD_HEY}!\p"
	.string "גם אני צעיר, אבל אני מחקה\n"
	.string "את סגנונות ודיבורם של\l"
	.string "זקני העיירה.\p"
	.string "מה תגיד, צעיר{ADD_HEY}?\n"
	.string "האם תסכי{SWAP_MEM}{ADD_YUD} שאלמד את מהלך\l"
	.string "חיקוי לפוקימון שלך?$"

MoveTutor_MimicDeclined:
	.string "או, חבל! רציתי ללמד חיקוי\n"
	.string "לפוקימון שלך!$"

MoveTutor_Text_MimicWhichMon:
	.string "פופו! והנה אעשה זאת!\n"
	.string "הרא{EMIT_HEY}{ADD_YUD} לי את הפוקימון\l"
	.string "שאת{EMIT_HEY} רוצה שאלמד.$"

MoveTutor_Text_MimicTaught:
	.string "חיקוי הוא מהלך עמוק.\p"
	.string "האם תוכל{ADD_YUD} לבצע אותו\n"
	.string "בצורה מושלמת כמוני…?$"

MoveTutor_Text_MetronomeTeach:
	.string "אני רוצה המון דברים!\n"
	.string "אבל כבר השתמשתי בקצבה שלי…\p"
	.string "האם לא יהיה נחמד אם קיים\n"
	.string "קסם שגורם לכסף להופיע\l"
	.string "כשמנפנפים באצבע?\p"
	.string "אם תרצ{EMIT_HEY}, TBH אוכל ללמד את המהלך\n"
	.string "פעמון לפוקימון שלך.\p"
	.string "כסף לא יופיע, אבל הפוקימון\n"
	.string "ינפנף את אצבעו. כן?$"

MoveTutor_Text_MetronomeDeclined:
	.string "בסדר.אני  אהיה כאן אם תשנ{EMIT_HEY}{ADD_YUD}\n"
	.string "את דעתך.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "אוקיי! אני אלמד אותו!\n"
	.string "איזה פוקימון ללמד?$"

MoveTutor_Text_MetronomeTaught:
	.string "כשפוקימון מניד את אצבעו\n"
	.string "כמו פעמון, קורים דברים נחמדים.\l"
	.string "האם זה לא יהיה נחמד אם גם\p"
	.string "אנחנו נוכל להשתמש בזה?$"

MoveTutor_Text_SleepTalkTeach:
	.string "האמפ! אשתי סומכת על כוח חבוי\n"
	.string "כדי להישאר ערה.\p"
	.string "היא צריכה פשוט לקחת תנומה כמוני,\n"
	.string "ולדבר בזמן שינה.\p"
	.string "אני יכול ללמד את הפוקימון שלך\n"
	.string "איך לדבר בזמן שינה. מעוניי{SWAP_NUN}{ADD_TAF}?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "או, בסדר, בסדר. את{EMIT_HEY} רוצה גם להישאר ער{ADD_HEY}\n"
	.string "בעזרת כוח חבוי…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "אה, ילד{ADD_HEY} שמערי{SWAP_CHAF}{ADD_HEY}!\n"
	.string "איזה פוקימון ללמד?$"

MoveTutor_Text_SleepTalkTaught:
	.string "מעולם לא הצלחתי בביצוע הטריק\n"
	.string "של אשתי.\p"
	.string "אני אשמח אם אצליח אפילו בזמן\n"
	.string "שאני מדבר בזמן שינה…$"

MoveTutor_Text_SubstituteTeach:
	.string "כשאני מביטה בעולם הרחב\n"
	.string "מעל הגג…\p"
	.string "אני חושבת כמה נחמד זה היה\n"
	.string "אם היה יותר מאחד ממני\l"
	.string "ואוכל לחוות כל מיני חיים שונים.\p"
	.string "כמובן שזה בלתי אפשרי.\n"
	.string "צחקוק…\p"
	.string "אני יודעת. האם תרצ{EMIT_HEY}{ADD_YUD} שפוקימון ילמד\n"
	.string "ממלא מקום?$"

MoveTutor_Text_SubstituteDeclined:
	.string "או, לא?\p"
	.string "פוקימון יכול ליצור העתק של עצמו\n"
	.string "בעזרת זה, את{EMIT_HEY} יודע{ADD_TAF}.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "צחקוק…\n"
	.string "איזה פוקימון תרצ{EMIT_HEY}{ADD_YUD} שאלמד\l"
	.string "את ממלא מקום?$"

MoveTutor_Text_SubstituteTaught:
	.string "אנחנו בני האדם צריכים\n"
	.string "להנות מהחיים עד הסוף!\p"
	.string "אני מקווה שגם את{EMIT_HEY} תגיע{ADD_YUD} לשם!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "אני כבר לא יכול לעשות את זה יותר!\p"
	.string "זה חסר תקווה!\p"
	.string "אני מאמן מסוג לחימה,\n"
	.string "ולכן קשה לי לנצח במכון מוסדיפ\l"
	.string "לא משנה כמה קשה אני אנסה!\p"
	.string "אחח! מכה! מכה! מכה!\n"
	.string "מכה! מכה! מכה!\p"
	.string "מה? אל תסתכל{ADD_YUD} עלי ככה!\n"
	.string "אני רק מכה באדמה!\p"
	.string "או שאולי תרצ{EMIT_HEY}{ADD_YUD} שאלמד את\n"
	.string "אגרוף דינמי לפוקימון שלך?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "חבל! את{EMIT_HEY} אפילו צוחק{ADD_TAF} עלי?\n"
	.string "מכה! מכה! מכה!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "מה? את{EMIT_HEY} כן? את{EMIT_HEY} אדם טוב!\n"
	.string "איזה פוקימון אלמד?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "אני רוצה שתנצח במכון מוסדיפ\n"
	.string "בעזרת אגרוף דינמי הזה!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "אנחה…\p"
	.string "מנהיג מכון הכושר של סוטופוליס\n"
	.string "מרתק במידה שאי אפשר להתעלם.\p"
	.string "אבל זה גם אומר שיש לי הרבה\n"
	.string "מתחרים על תשומת לבו.\p"
	.string "יש לו קסם עם חרב פיפיות.\n"
	.string "אני לא הצלחתי למשוך את מבטו.\p"
	.string "בבקשה, ת{SWAP_NUN}{ADD_YUD} לי ללמד את הפוקימון\n"
	.string "את המהלך חרב פיפיות!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "או…\n"
	.string "אפילו את{EMIT_HEY} דחית אותי…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "אוקיי, איזה פוקימון אלמד\n"
	.string "את חרב פיפיות?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "אני לא אחיה בשביל אהבה יותר!\n"
	.string "אני אהפוך לקשוח!$"

MoveTutor_Text_ExplosionTeach:
	.string "אני לא מתכוון לללכת לשום מקום מהר\n"
	.string "באזור ככה לנצח.\p"
	.string "תסתכל{ADD_YUD}, אני אעזוב לעיר\n"
	.string "ואהיה להיט גדול.\p"
	.string "ברצינות, אני עומד לגרום\n"
	.string "לפיצוץ של פופולריות!\p"
	.string "אם שמעת זאת, אשמח ללמד\n"
	.string "פיצוץ לפוקימון שלך!$"

MoveTutor_Text_ExplosionDeclined:
	.string "גאאה! את{EMIT_HEY} דוחה אותי כי אני גר\n"
	.string "בפרברים?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "בסדר! אז זה יהיה פיצוץ!\n"
	.string "איזה פוקימון רוצה להתפוצץ?$"

MoveTutor_Text_ExplosionTaught:
	.string "להרבה זמן, אני לימדתי פוקימונים\n"
	.string "איך להשתמש בפיצוץ, אבל עדיין\l"
	.string "לא הצלחתי להצית את הפיצוץ שלי…\p"
	.string "אולי עמוק בפנים אני מעדיף\n"
	.string "להישאר כאן…$"
