gText_ObtainedTheItem::
	.string "השיג{ADD_HEY} את ה{STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "התיק מלא…$"

gText_PutItemInPocket::
	.string "{PLAYER} הניח{ADD_HEY} בצד את {STR_VAR_2}\n"
	.string "בתא ה{STR_VAR_3}.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} מצא{ADD_HEY} {STR_VAR_2} אחד!$"

gText_TooBadBagIsFull::
	.string "חבל מאוד!\n"
	.string "התיק מלא…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} הניח{ADD_HEY} בצד את ה{STR_VAR_2}\n"
	.string "בתיק.$"

gText_ObtainedTheDecor::
	.string "השיג{ADD_HEY} את ה{STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "חבל מאוד! אין יותר מקום לעוד\n"
	.string "{STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "ה{STR_VAR_2} הועבר\n"
	.string "למחשב.$"
