gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} הועבר למחשב\n"
	.string "של מישהו.\p"
	.string "הוא הונח\n"
	.string "בקופסה ”{STR_VAR_1}.“$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} הועבר למחשב\n"
	.string "של לאנט.\p"
	.string "הוא הונח\n"
	.string "בקופסה ”{STR_VAR_1}.“$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "הקופסה ”{STR_VAR_3}“ במחשב\n"
	.string "של מישהו מלאה.\p"
	.string "{STR_VAR_2} הועבר\n"
	.string "לקופסה ”{STR_VAR_1}.“$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "הקופסה ”{STR_VAR_3}“ במחשב\n"
	.string "של לאנט מלאה.\p"
	.string "{STR_VAR_2} הועבר\n"
	.string "לקופסה ”{STR_VAR_1}.“$"

gText_NoMoreRoomForPokemon::
	.string "אין יותר מקום לפוקימון!\p"
	.string "קופסאות הפוקימון מלאות ולא\n"
	.string "יכולות לקבל עוד!$"

gText_NicknameThisPokemon::
	.string "האם ברצונך לתת כינוי\n"
	.string "ל{STR_VAR_1} הזה?$"
