gText_WouldYouLikeToRestYourPkmn::
	.string "שלום, וברו{SWAP_CHAF}{ADD_HEY} הבא{ADD_HEY}\n"
	.string "למרכז הפוקימון.\p"
	.string "אנו מחזירים את הפוקימונים העייפים\n"
	.string "שלך לבריאות שלמה.\p"
	.string "האם תרצ{EMIT_HEY}{ADD_YUD} לתת לפוקימון שלך מנוחה?$"

gText_IllTakeYourPkmn::
	.string "אוקיי, אני אקח את הפוקימון שלך\n"
	.string "לכמה שניות.$"

gText_RestoredPkmnToFullHealth::
	.string "תודה שחיכית.\p"
	.string "החזרנו את הפוקימון שלך\n"
	.string "לבריאות מלאה.$"

gText_WeHopeToSeeYouAgain::
	.string "אנו מקווים לראותך שוב!$"

gText_WelcomeCutShort::
	.string "שלום, וברו{SWAP_CHAF}{ADD_HEY} הבא{ADD_HEY}\n"
	.string "למרכז הפוקימון.\p"
	.string "אנו מחזירים את הפוקימונים העייפים\n"
	.string "שלך לבריאות שלמה.\p"
	.string "האם תרצ…$"

gText_NoticesGoldCard::
	.string "ה-הכרטיס הזה…\n"
	.string "היתכן… זה הכרטיס זהב?!\p"
	.string "הו, צבע הזהב מבריק!\n"
	.string "ארבעת הכוכבים מנצנצים!\p"
	.string "ראיתי כמה מאמנים עם\n"
	.string "כרטיס כסף בעבר, אבל, {PLAYER},\l"
	.string "את{EMIT_HEY} המאמ{SWAP_NUN}{ADD_TAF} הראשו{SWAP_NUN}{ADD_HEY} שאני רואה\l"
	.string "עם כרטיס זהב!\p"
	.string "אוקיי, {PLAYER}, בבקשה הרש{EMIT_HEY}{ADD_YUD} לי\n"
	.string "את הכבוד לתת לפוקימון שלך מנוחה!$"

gText_YouWantTheUsual::
	.string "אני שמחה לראות אותך, {PLAYER}!\n"
	.string "את{EMIT_HEY} רוצה את הרגיל, נכון?$"

gText_IllTakeYourPkmn2::
	.string "אוקיי, אני אקח את הפוקימון שלך\n"
	.string "לכמה שניות.$"

gText_ThankYouForWaiting::
	.string "תודה שחיכית.$"

gText_WeHopeToSeeYouAgain2::
	.string "אנו מקווים לראותך שוב!$"
