gBirchDexRatingText_AreYouCurious::
	.string "פרופ. בירץ': אה, {PLAYER}{KUN}!\p"
	.string "את{EMIT_HEY} סקר{SWAP_NUN}{ADD_YUD}{ADD_TAF} לגבי איך הפוקידע\n"
	.string "שלך מתקדם?$"

gBirchDexRatingText_Cancel::
	.string "המ? או, לא תפסיק מספיק\n"
	.string "פוקימון כדי שיהיה כדאי.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "המהמ…\p"
	.string "אז, ראית {STR_VAR_1} פוקימון,\n"
	.string "ותפסת {STR_VAR_2} פוקימון…$"

gBirchDexRatingText_LessThan10::
	.string "ל{SWAP_CHAF}{ADD_YUD} לאזורים עם דשא ותחפש{ADD_YUD}\n"
	.string "פוקימון בזהירות.$"

gBirchDexRatingText_LessThan20::
	.string "נראה שהתחלת לקלוט איך זה עובד.\n"
	.string "אבל מכאן זה נהיה קשה יותר.$"

gBirchDexRatingText_LessThan30::
	.string "חלק מהפוקימונים מופיעים רק\n"
	.string "באזורים מסוימים.\l"
	.string "את{EMIT_HEY} צריך להיות סבלני{ADD_TAF}.$"

gBirchDexRatingText_LessThan40::
	.string "ובכן, זה יכול להכיל יותר,\n"
	.string "אבל זה נראה יותר כמו\l"
	.string "פוקידע עכשיו.$"

gBirchDexRatingText_LessThan50::
	.string "זה מתקדם יפה מאוד.\n"
	.string "תמשי{SWAP_CHAF}{ADD_YUD} במאמץ.$"

gBirchDexRatingText_LessThan60::
	.string "האם את{EMIT_HEY} משתמש בחכה כלשהי?\n"
	.string "יש הרבה פוקימון בים.$"

gBirchDexRatingText_LessThan70::
	.string "חוץ מרק לתפוס פוקימון,\n"
	.string "מה לגבי גם לגרום להם להתפתח?$"

gBirchDexRatingText_LessThan80::
	.string "זה הולך להיות פוקידע\n"
	.string "פנטסטי.\l"
	.string "זה הרושם שאני מקבל.$"

gBirchDexRatingText_LessThan90::
	.string "אספת כל כך הרבה…\n"
	.string "הכישרון שלך יוצא מן הכלל!$"

gBirchDexRatingText_LessThan100::
	.string "ביקרת באזור הספארי?\p"
	.string "שמעתי שיש שם פוקימון שניתן\n"
	.string "לתפוס רק שם.$"

gBirchDexRatingText_LessThan110::
	.string "סוף סוף הגעת\n"
	.string "לסף 001 המינים.\p"
	.string "זה פוקידע מרשים!$"

gBirchDexRatingText_LessThan120::
	.string "אולי יש פוקימון שניתן למצוא\n"
	.string "רק על ידי ריסוק אבן.$"

gBirchDexRatingText_LessThan130::
	.string "את{EMIT_HEY} צרי{SWAP_CHAF}{ADD_HEY} להשיג עוד פוקימון\n"
	.string "על ידי החלפה עם אחרים.$"

gBirchDexRatingText_LessThan140::
	.string "שמעתי על פוקימון שמתפתחים\n"
	.string "כשהם מגיעים לאהבה מלאה\l"
	.string "למאמניהם.$"

gBirchDexRatingText_LessThan150::
	.string "לא היה לי מושג שיש כל כך\n"
	.string "הרבה מיני פוקימון במחוז\l"
	.string "הואן.$"

gBirchDexRatingText_LessThan160::
	.string "מדי פעם, חלק מהפוקימונים מופיעים\n"
	.string "במספרים גדולים בזמן התפרצויות.\p"
	.string "אל תפספס{ADD_YUD} הזדמנויות\n"
	.string "כאלה.$"

gBirchDexRatingText_LessThan170::
	.string "אפשר להבין טוב יותר\n"
	.string "את הפוקימון במחוז הואן\l"
	.string "על ידי הצצה בפוקידע שלך.$"

gBirchDexRatingText_LessThan180::
	.string "אני אומר שאת{EMIT_HEY} כבר מוסמ{SWAP_CHAF}{ADD_TAF} בתור\n"
	.string "פרופסור לפוקימון, וגם\l"
	.string "אחד טוב!$"

gBirchDexRatingText_LessThan190::
	.string "עם פוקידע כזה מושלם,\n"
	.string "את{EMIT_HEY} ממש מקצוע{SWAP_NUN}{ADD_YUD}{ADD_TAF} בזה!$"

gBirchDexRatingText_LessThan200::
	.string "את{EMIT_HEY} ממש קרוב{ADD_HEY} להשלים\n"
	.string "את הפוקידע הזה\l"
	.string "אני מרגיש את זה בעצמותיי!$"

gBirchDexRatingText_DexCompleted::
	.string "ברכות!\n"
	.string "הפוקידע שלך הושלם!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "המהמ…\n"
	.string "מבחינה ארצית…\p"
	.string "ראית {STR_VAR_1} פוקימון,\n"
	.string "ותפסת {STR_VAR_2} פוקימון…$"
