Questionnaire_Text_FillOut::
	.string "יש שאלון.\n"
	.string "האם תרצ{EMIT_HEY}{ADD_YUD} למלא אותו?$"

Questionnaire_Text_ThankYou::
	.string "תודה שהקדשת מזמנך\n"
	.string "למילוי השאלון שלנו.\p"
	.string "המשוב שלך ישמש\n"
	.string "להתייחסות עתידית.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "אה, שלום!\n"
	.string "את{EMIT_HEY} מכיר{ADD_HEY} את המילים האלו?\p"
	.string "זה אומר שאת{EMIT_HEY} חייב{ADD_TAF} לדעת על\n"
	.string "המתנה המסתורית.\p"
	.string "מעתה והלאה, תוכל{ADD_YUD} לקבל\n"
	.string "מתנות מסתוריות!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "ברגע ששמרת את המשחק, תוכל{ADD_YUD}\n"
	.string "לגשת למתנה מסתורית.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "אה, שלום!\n"
	.string "את{EMIT_HEY} מכיר{ADD_HEY} את המילים האלו?\p"
	.string "זה אומר שאת{EMIT_HEY} חייב{ADD_TAF} לדעת על\n"
	.string "אירוע מסתורי.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "ברגע ששמרת את המשחק, תוכל{ADD_YUD}\n"
	.string "לגשת לאירוע מסתורי.$"

MysteryGift_Text_TheresATicketForYou::
	.string "תודה שהשתמשת במערכת אירוע\n"
	.string "מסתורי.\p"
	.string "את{EMIT_HEY} כנראה {PLAYER}.\n"
	.string "יש כאן כרטיס בשבילך.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "נראה שזה מיועד לשימוש\n"
	.string "בנמל בעיר ליליקוב.\p"
	.string "למה שלא תנס{EMIT_HEY}{ADD_YUD} אותו ותרא{EMIT_HEY}{ADD_YUD}\n"
	.string "על מה מדובר?$"
