	.align 2
gText_ConfirmSave::
	.string "האם תרצ{EMIT_HEY}{ADD_YUD} לשמור את המשחק?$"

gText_AlreadySavedFile::
	.string "כבר קיים קובץ שמור.\n"
	.string "האם זה בסדר לדרוס אותו?$"

gText_SavingDontTurnOff::
	.string "שומר…\n"
	.string "נא לא לכבות את המכשיר.$"

gText_PlayerSavedGame::
	.string "{PLAYER} שמר{ADD_HEY} את המשחק.$"

gText_DifferentSaveFile::
	.string "אזהרה!\p"
	.string "יש קובץ משחק אחר שכבר נשמר.\p"
	.string "אם תשמ{EMIT_VAV}ר{ADD_YUD} עכשיו, ההרתפקה של הקובץ\n"
	.string "האחר, כולל פריטים ופוקימון,\l"
	.string "יאבדו לחלוטין.\p"
	.string "האם את{EMIT_HEY} בטוח{ADD_HEY} שאת{EMIT_HEY} רוצה לשמור עכשיו\n"
	.string "ולהחליף את קובץ השמירה האחר?$"

gText_SaveError::
	.string "שגיאת שמירה.\p"
	.string "נא להחליף את\n"
	.string "הזיכרון גיבוי.$"

gText_SavingDontTurnOffPower::
	.string "שומר…\n"
	.string "נא לא לכבות את המכשיר.$"
