SecretBase_Text_Trainer0Intro:
	.string "כבר הכנת בסיס סודי?\p"
	.string "טיילתי לכאן, לשם, לכל מקום לפני\n"
	.string "שבחרתי את המקום הזה.\p"
	.string "מכיוון שאת{EMIT_HEY} כבר פה, מה דעתך\n"
	.string "על קרב?$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "אוקיי!\n"
	.string "הנה אנחנו באים!$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "הא?\n"
	.string "או, את{EMIT_HEY} לא יכול{ADD_HEY} עכשיו…$"

SecretBase_Text_Trainer0Defeated::
.string "וואאאר! את{EMIT_HEY} חזק{ADD_HEY} מדי!\n"	  
	.string "לגבי ההפסד שלי… בבקשה תשמ{EMIT_VAV}ר{ADD_YUD} את זה בסוד!$"

SecretBase_Text_Trainer0PostBattle:
	.string "מה את{EMIT_HEY} חושב{ADD_TAF} על הבסיס הסודי שלי?\n"
.string "בוא{ADD_YUD} לבקר אותי שוב מחר.$"    

SecretBase_Text_Trainer0PreChampion:
.string "כבר הכנת בסיס סודי?\p"	   
	.string "טיילתי לכאן, לשם, לכל מקום לפני\n"
	.string "שבחרתי את המקום הזה.\p"
	.string "תרגיש{ADD_YUD} חופשי להסתובב!$"

SecretBase_Text_Trainer5Intro:
.string "יש הרבה מקומות שבהם\n"	   
	.string "אפשר להכין בסיס סודי.\p"
	.string "אבל אני אוהב את הנקודה הזו הכי הרבה.\n"
	.string "את{EMIT_HEY} לא חושב{ADD_TAF} שזה נחמד?\p"
	.string "או, תרצ{EMIT_HEY}{ADD_YUD} לערוך קרב?$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "אוקיי, הנה זה בא!$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "או…\n"
	.string "את{EMIT_HEY} לא יכול{ADD_HEY} עכשיו, אוקיי.$"

SecretBase_Text_Trainer5Defeated::
.string "המממ… זה ההפסד שלנו…\n"	
	.string "אבל אל תספר{ADD_YUD} לאף אחד!\l"
	.string "זה סוד חסוי!$"

SecretBase_Text_Trainer5PostBattle:
.string "אם את{EMIT_HEY} שוב באזור הזה,\n"	  
	.string "אני מקווה שתבקר{ADD_YUD} אותי.$"

SecretBase_Text_Trainer5PreChampion:
.string "יש הרבה מקומות שבהם אפשר\n"	
	.string "להכין בסיס סודי.\p"
	.string "אבל אני אוהב את הנקודה הזו הכי הרבה.\n"
	.string "את{EMIT_HEY} לא חושב{ADD_TAF} שזה נחמד?$"

SecretBase_Text_Trainer1Intro:
	.string "זוהי נקודה פופולרית.\n"
	.string "היא תמיד תפוסה.\p"
	.string "או! חשבת גם על\n"
	.string "לתפוס את הנקודה הזו?\p"
	.string "אני אגיד לך מה, את{EMIT_HEY} יכול{ADD_HEY} לקבל את\n"
	.string "הנקודה אם תצליח{ADD_YUD} להביס אותי.$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "אוקיי!\n"
	.string "אני הולך להגן על הבסיס הסודי שלי!$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "האא? אכן כך?\n"
	.string "את{EMIT_HEY} לא מעוניי{SWAP_NUN}{ADD_TAF} בנקודה הזו?$"

SecretBase_Text_Trainer1Defeated::
	.string "אני לא יכול להמשיך!\n"
	.string "אני נכנע!$"

SecretBase_Text_Trainer1PostBattle:
	.string "אוקיי, כשאני אעבור יום אחד,\n"
	.string "המקום הזה יהיה שלך!$"

SecretBase_Text_Trainer1PreChampion:
	.string "זוהי נקודה פופולרית.\n"
	.string "היא תמיד תפוסה.\p"
.string "חיכיתי הרבה זמן עד שהיא תתפנה.\n"	  
	.string "סוף סוף זכיתי להשתמש בה!$"

SecretBase_Text_Trainer6Intro:
	.string "ברו{SWAP_CHAF}{ADD_HEY} הבא{ADD_HEY} למעבדת הפוקימון שלי.\p"
.string "אני עורך מחקר על קרבות\n"	  
	.string "בסודיות.\p"
	.string "תרצ{EMIT_HEY}{ADD_YUD} לראות כמה אני חזק?$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "אני הולך לתת את כל כולי!$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "או.\n"
	.string "אז בפעם אחרת!$"

SecretBase_Text_Trainer6Defeated::
.string "הממ… עדיין יש לי הרבה ללמוד.\n"	
	.string "אני חייב ללמוד עוד.$"

SecretBase_Text_Trainer6PostBattle:
	.string "תודה על הקרב מולי.\n"
	.string "בבקשה תחז{EMIT_VAV}ר{ADD_YUD} שוב מחר.$"

SecretBase_Text_Trainer6PreChampion:
	.string "ברו{SWAP_CHAF}{ADD_HEY} הבא{ADD_HEY} למעבדת הפוקימון שלי.\p"
.string "אני עורך מחקר על קרבות\n"	  
	.string "בסודיות.\p"

SecretBase_Text_Trainer2Intro:
	.string "אחוזה גדולה זה נחמד, אבל אני אוהב יותר\n"
	.string "מקום שכזה.\p"
.string "אני אוהב את זה כי כל מיני אנשים\n"	   
	.string "באים לבקר אותי.\p"
	.string "אז, מה דעתך על קרב?$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "ככה צריך!$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "כשאת{EMIT_HEY} מוכ{SWAP_NUN}{ADD_HEY}, תקרא{ADD_YUD} לי!$"

SecretBase_Text_Trainer2Defeated::
	.string "אוו! נגמר!\n"
	.string "אבל זה עדיין כיף להילחם!$"

SecretBase_Text_Trainer2PostBattle:
.string "טוב, בכל מקרה, אני צריך ללכת לקנות\n"	  
	.string "קצת קישוטים וריהוט.\p"
	.string "אני רוצה שהבסיס הסודי שלי יהיה מקום\n"
	.string "שאנשים אחרים יכולים ליהנות ממנו.$"

SecretBase_Text_Trainer2PreChampion:
	.string "אחוזה גדולה זה נחמד, אבל אני אוהב יותר\n"
	.string "מקום שכזה.\p"
.string "אני אוהב את זה כי כל מיני אנשים\n"	   
	.string "באים לבקר אותי.$"

SecretBase_Text_Trainer7Intro:
.string "אני פשוט מעריץ קניות של קישוטים\n"
	.string "וריהוט.\p"
	.string "אני גם אוהב לגדל פוקימונים בדיוק\n"
	.string "באותה מידה.\p"
	.string "אם תהי{EMIT_HEY}{ADD_YUD} כל כך אדיב{ADD_HEY}, תילח{SWAP_MEM}{ADD_YUD}\n"
	.string "מול הפוקימונים שלי?$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "תודה לך.\n"
	.string "נתחיל?$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "או.\n"
	.string "כמה מאכזב…$"

SecretBase_Text_Trainer7Defeated::
	.string "אני נכנע…$"

SecretBase_Text_Trainer7PostBattle:
	.string "זה הכל היה בכיף גדול!\n"
	.string "אני צריך ללכת להנות מקניות עכשיו.$"

SecretBase_Text_Trainer7PreChampion:
.string "אני פשוט מעריץ קניות של קישוטים\n"	   
	.string "וריהוט.\p"
.string "אני גם אוהב לגדל פוקימונים בדיוק\n"	
	.string "באותה מידה.$"

SecretBase_Text_Trainer3Intro:
.string "יש אנשים שמכינים את הבסיסים הסודיים שלהם\n"	
	.string "במקומות קשים למציאה.\l"
	.string "האם הם רוצים פשוט להסתתר?\p"
	.string "אבל מכיוון שמצאת אותי, מה דעתך\n"
	.string "שנערוך קרב?$"

SecretBase_Text_Trainer3AcceptBattle:
.string "אני לא הולך להיכנע בקלות!$"	

SecretBase_Text_Trainer3DeclineBattle:
	.string "או… אולי את{EMIT_HEY} עיי{SWAP_PEY}{ADD_HEY} מלחפש\n"
	.string "את המקום הזה?$"

SecretBase_Text_Trainer3Defeated::
	.string "נפלתי…$"

SecretBase_Text_Trainer3PostBattle:
	.string "איפה הבסיס הסודי שלך?\n"
	.string "אני צריך לבוא לבקר אותך שם.$"

SecretBase_Text_Trainer3PreChampion:
.string "יש אנשים שמכינים את הבסיסים הסודיים שלהם\n"	
	.string "במקומות קשים למציאה.\l"
	.string "האם הם רוצים פשוט להסתתר?$"

SecretBase_Text_Trainer8Intro:
.string "אנשים אמרו לי שאפשר להשיג\n"
	.string "קישוטים בכמה דרכים.\p"
	.string "אנחנו צריכים לערוך מרוץ כדי לראות מי יכול\n"
	.string "להשיג קישוטים וריהוט יפים יותר!\p"
	.string "בינתיים, רוצה קרב?$"

SecretBase_Text_Trainer8AcceptBattle:
.string "זה הבסיס הסודי שלי.\n"	   
	.string "אני לא יכול להפסיד!$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "אני אלחם מולך בכל עת.$"

SecretBase_Text_Trainer8Defeated::
	.string "הא?\n"
	.string "האם הרגע הפסדתי?$"

SecretBase_Text_Trainer8PostBattle:
	.string "אני לא אפסיד באיסוף קישוטים.\n"
	.string "בוא{ADD_YUD} לבקר שוב!$"

SecretBase_Text_Trainer8PreChampion:
.string "אנשים אמרו לי שאפשר להשיג\n"	 
	.string "קישוטים בכמה דרכים.\p"
	.string "אנחנו צריכים לערוך מרוץ כדי לראות מי יכול\n"
	.string "להשיג קישוטים וריהוט יפים יותר!$"

SecretBase_Text_Trainer4Intro:
.string "מצאתי נקודה שאהבתי, ועיצבתי אותה\n"	
	.string "עם הקישוטים האהובים עלי.\p"
	.string "אני מגדל את הפוקימון האהוב עלי ומתחזק\n"
	.string "איתו.\p"
	.string "זה מה שאני עושה.\n"
	.string "רוצה להילחם איתי?$"

SecretBase_Text_Trainer4AcceptBattle:
.string "הרא{EMIT_HEY}{ADD_YUD} לי ממה את{EMIT_HEY} עשוי{ADD_HEY}!$"	

SecretBase_Text_Trainer4DeclineBattle:
.string "אני מניח שיש זמנים שבהם את{EMIT_HEY} לא\n"    
	.string "בעניין.$"

SecretBase_Text_Trainer4Defeated::
.string "אני יודע בדיוק ממה את{EMIT_HEY} עשוי{ADD_HEY} עכשיו.$"	   

SecretBase_Text_Trainer4PostBattle:
.string "שנינו יכולים להתחזק.\n"	
	.string "בוא{ADD_YUD} נמשיך בזה!$"

SecretBase_Text_Trainer4PreChampion:
.string "מצאתי נקודה שאהבתי, ועיצבתי אותה\n"	
	.string "עם הקישוטים האהובים עלי.\p"
	.string "אני מגדל את הפוקימון האהוב עלי ומתחזק\n"
	.string "איתו.\p"
	.string "כל יום הוא יום נהדר.$"

SecretBase_Text_Trainer9Intro:
.string "אפשר ללמוד הרבה על הטעם\n"	   
	.string "והחוש של אנשים לפי סוגי\l"
	.string "הקישוטים שיש להם, ואיך הם\l"
	.string "מציגים אותם.\p"
	.string "מה את{EMIT_HEY} חושב{ADD_TAF} על הטעם שלי?\n"
	.string "את{EMIT_HEY} חסר{ADD_TAF} מילים?\p"
	.string "רוצה לראות את הטעם שלי בקרבות?"

SecretBase_Text_Trainer9AcceptBattle:
	.string "אין התאפקות!$"

SecretBase_Text_Trainer9DeclineBattle:
.string "אשמח להדגים את הסגנון שלי\n"	 
	.string "בכל עת.$"

SecretBase_Text_Trainer9Defeated::
.string "את{EMIT_HEY} מוכשר{ADD_TAF} בצורה יוצאת דופן!\n"	
	.string "הכוח שלך נראה בלתי מוגבל…$"

SecretBase_Text_Trainer9PostBattle:
.string "מה חשבת על הסגנון שלי?\n"	  
	.string "אני אמשיך לשפשף אותו!$"

SecretBase_Text_Trainer9PreChampion:
.string "אפשר ללמוד הרבה על הטעם\n"	   
	.string "והחוש של אנשים לפי סוגי\l"
	.string "הקישוטים שיש להם, ואיך הם\l"
	.string "מציגים אותם.\p"
	.string "מה את{EMIT_HEY} חושב{ADD_TAF} על הטעם שלי?\n"
	.string "את{EMIT_HEY} חסר{ADD_TAF} מילים?$"
