ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "האם את{EMIT_HEY} מתכנ{SWAP_NUN}{ADD_TAF} להיכנס פנימה?\p"
	.string "אולי תביא{ADD_YUD} לי קצת מלח שרטון\n"
	.string "וצדפות שרטון?\p"
	.string "אם תביא{ADD_YUD} לי את המרכיבים האלו,\n"
	.string "אכין לך משהו טוב.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "אם תביא{ADD_YUD} לי ארבע מכל אחד -\n"
	.string "מלח שרטון וצדפת שרטון,\l"
	.string "אני אוכל להכין לך פעמון צדפה…\p"
	.string "תוכל{ADD_YUD} להשיג את המרכיבים האלהs\n"
	.string "כל יום.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "או, היי! מלח שרטון וצדפות שרטון!\n"
	.string "וגם יש מספיק מהם!\p"
	.string "האם תרצ{EMIT_HEY}{ADD_YUD} שאכין לך\n"
	.string "פעמון צדפה איתם?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "בסדר גמור! אני אכין לך\n"
	.string "פעמון צדפה מיד.\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "זהו! סיימתי!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "ת{SWAP_NUN{ADD_YUD} לפוקימון שלך להחזיק בזה}.\n"
	.string "הוא יאהב את זה, זה בטוח.\p"
	.string "ובכן, הצליל של פעמון הצדפה…\n"
	.string "הוא פשוט נפלא!\p"
	.string "תוכל{ADD_YUD} להשיג את המרכיבים בכל יום,\n"
	.string "כך שאוכל להכין לך עוד.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "או… באמת…\n"
	.string "רציתי להכין פעמון צדפה…$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "אין לך מקום בתיק שלך\n"
	.string "אם הייתי מכין לך את זה.\p"
	.string "עליך לפנות מקום ולחזור\n"
	.string "בשביל הפעמון צדפה.$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "היה כאן קצת מלח שרטון.\n"
	.string "אבל, עכשיו אין כאן כלום.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "היה כאן כמה צדפות שרטון.\n"
	.string "אבל, עכשיו אין כאן כלום.$"
