gTrickHouse_Mechadoll_Oddish::
	.string "{STR_VAR_1}$"

gTrickHouse_Mechadoll_Poochyena::
	.string "{STR_VAR_2}$"

gTrickHouse_Mechadoll_Taillow::
	.string "{STR_VAR_3}$"

gTrickHouse_Mechadoll_Azurill::
	.string "{STR_VAR_1}$"

gTrickHouse_Mechadoll_Lotad::
	.string "{STR_VAR_2}$"

gTrickHouse_Mechadoll_Wingull::
	.string "{STR_VAR_3}$"

gTrickHouse_Mechadoll_Dustox::
	.string "{STR_VAR_1}$"

gTrickHouse_Mechadoll_Zubat::
	.string "{STR_VAR_2}$"

gTrickHouse_Mechadoll_Nincada::
	.string "{STR_VAR_3}$"

gTrickHouse_Mechadoll_Ralts::
	.string "{STR_VAR_1}$"

gTrickHouse_Mechadoll_Zigzagoon::
	.string "{STR_VAR_2}$"

gTrickHouse_Mechadoll_Slakoth::
	.string "{STR_VAR_3}$"

gTrickHouse_Mechadoll_Poochyena2::
	.string "{STR_VAR_1}$"

gTrickHouse_Mechadoll_Shroomish::
	.string "{STR_VAR_2}$"

gTrickHouse_Mechadoll_Zigzagoon2::
	.string "{STR_VAR_3}$"

gTrickHouse_Mechadoll_Poochyena3::
	.string "{STR_VAR_1}$"

gTrickHouse_Mechadoll_Zubat2::
	.string "{STR_VAR_2}$"

gTrickHouse_Mechadoll_Carvanha::
	.string "{STR_VAR_3}$"

gTrickHouse_Mechadoll_BurnHeal::
	.string "ריפוי כויה$"

gTrickHouse_Mechadoll_HarborMail::
	.string "מכתב נמל$"

gTrickHouse_Mechadoll_SamePrice::
	.string "אותו מחיר$"

gTrickHouse_Mechadoll_60Yen::
	.string "06¥$"

gTrickHouse_Mechadoll_55Yen::
	.string "55¥$"

gTrickHouse_Mechadoll_Nothing::
	.string "כלום$"

gTrickHouse_Mechadoll_CostMore::
	.string "הם יעלו יותר.$"

gTrickHouse_Mechadoll_CostLess::
	.string "הם יעלו פחות.$"

gTrickHouse_Mechadoll_SamePrice2::
	.string "אותו מחיר$"

gTrickHouse_Mechadoll_Male::
	.string "זכר$"

gTrickHouse_Mechadoll_Female::
	.string "נקבה$"

gTrickHouse_Mechadoll_Neither::
	.string "אף אחד מהם$"

gTrickHouse_Mechadoll_ElderlyMen::
	.string "גברים זקנים$"

gTrickHouse_Mechadoll_ElderlyLadies::
	.string "נשים זקנות$"

gTrickHouse_Mechadoll_SameNumber::
	.string "אותו מספר$"

gTrickHouse_Mechadoll_None::
	.string "כלום$"

gTrickHouse_Mechadoll_One::
	.string "1$"

gTrickHouse_Mechadoll_Two::
	.string "2$"

gTrickHouse_Mechadoll_Two2::
	.string "2$"

gTrickHouse_Mechadoll_Three::
	.string "3$"

gTrickHouse_Mechadoll_Four::
	.string "4$"

gTrickHouse_Mechadoll_Six::
	.string "6$"

gTrickHouse_Mechadoll_Seven::
	.string "7$"

gTrickHouse_Mechadoll_Eight::
	.string "8$"

gTrickHouse_Mechadoll_Six2::
	.string "6$"

gTrickHouse_Mechadoll_Seven2::
	.string "7$"

gTrickHouse_Mechadoll_Eight2::
	.string "8$"
