SootopolisCity_House7_MapScripts::
	.byte 0

SootopolisCity_House7_EventScript_OldMan::
	msgbox SootopolisCity_House7_Text_CityFromEruptedVolcano, MSGBOX_NPC
	end

SootopolisCity_House7_EventScript_PokefanF::
	msgbox SootopolisCity_House7_Text_CaveMadeToKeepSomething, MSGBOX_NPC
	end

SootopolisCity_House7_Text_CityFromEruptedVolcano:
	.string "הר געש תת-מימי התפרץ\n"
	.string "והציף את עצמו מהעומק.\p"
	.string "הפיר שלו צץ מהים\n"
	.string "ומלא במי גשמים.\p"
	.string "כך נוצרה העיר סוטופוליס.$"

SootopolisCity_House7_Text_CaveMadeToKeepSomething:
	.string "המערה שמחברת בין סוטופוליס\n"
	.string "לעולם החיצון…\p"
	.string "נראה כאילו המערה נוצרה כדי\n"
	.string "למנוע ממשהו לצאת.\p"
	.string "או שאולי אני פשוט מדמיינת?$"

