PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
	.string "נורמן נהפך למנהיג מכון\n"
	.string "העיר החדש שלנו.\p"
	.string "אני חושבת שהוא קרא למשפחה שלו\n"
	.string "ממקום רחוק.$"

PetalburgCity_House2_Text_BattledNormanOnce:
	.string "נלחמתי בנורמן פעם אחת, אבל, וואו,\n"
	.string "הוא היה חזק מדי.\p"
	.string "איך אני אתאר את זה?\p"
	.string "יש לי הרגשה שהוא פשוט\n"
	.string "חי עבור פוקימון.$"

