OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "כאשר קרב פוקימון מתחיל, האחד\n"
	.string "שבצד שמאל של הרשימה יוצא ראשון.\p"
	.string "אז, כשיש לך יותר פוקימון בקבוצה\n"
	.string "שלך, נס{EMIT_HEY}{ADD_YUD} לשנות את הסדר\l"
	.string "של הפוקימונים שלך.\p"
	.string "זה יכול לתת לך יתרון.$"

