PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "לטייל זה נפלא!\p"
	.string "כשהייתי צעיר, שוטטתי בימים\n"
	.string "ובהרים!$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "אנחה…\p"
	.string "הלוואי ויכולתי לצאת להרפתקה\n"
	.string "עם פוקימון…\p"
	.string "לזחול דרך עשב לח…\n"
	.string "לטפס הרים סלעיים ומחוספסים…\p"
	.string "לחצות את הימים הסוערים…\n"
	.string "לשוטט במערות חשוכות…\p"
	.string "ולפעמים, אפילו קצת\n"
	.string "געגועים הביתה…\p"
	.string "זה בטח נפלא לטייל!$"

