LavaridgeTown_HerbShop_MapScripts::
	.byte 0

LavaridgeTown_HerbShop_EventScript_Clerk::
	lock
	faceplayer
	message LavaridgeTown_HerbShop_Text_WelcomeToHerbShop
	waitmessage
	pokemart LavaridgeTown_HerbShop_Pokemart
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	release
	end

	.align 2
LavaridgeTown_HerbShop_Pokemart:
	.2byte ITEM_ENERGY_POWDER
	.2byte ITEM_ENERGY_ROOT
	.2byte ITEM_HEAL_POWDER
	.2byte ITEM_REVIVAL_HERB
	pokemartlistend

LavaridgeTown_HerbShop_EventScript_ExpertM::
	msgbox LavaridgeTown_HerbShop_Text_HerbalMedicineWorksButMonWillDislike, MSGBOX_NPC
	end

LavaridgeTown_HerbShop_EventScript_OldMan::
	lock
	faceplayer
	goto_if_set FLAG_RECEIVED_CHARCOAL, LavaridgeTown_HerbShop_EventScript_ExplainCharcoal
	msgbox LavaridgeTown_HerbShop_Text_YouveComeToLookAtHerbalMedicine, MSGBOX_DEFAULT
	giveitem ITEM_CHARCOAL
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_ShowBagIsFull
	setflag FLAG_RECEIVED_CHARCOAL
	release
	end

LavaridgeTown_HerbShop_EventScript_ExplainCharcoal::
	msgbox LavaridgeTown_HerbShop_Text_ExplainCharcoal, MSGBOX_DEFAULT
	release
	end

LavaridgeTown_HerbShop_Text_WelcomeToHerbShop:
	.string "ברוכים הבאים לחנות העשבים, ביתם של\n"
	.string "תרופות יעילות וזולות!$"

LavaridgeTown_HerbShop_Text_YouveComeToLookAtHerbalMedicine:
	.string "את{EMIT_HEY} באת להסתכל על תרופות צמחיות\n"
	.string "בלברידג'?\p"
	.string "זה בהחלט נשמע משובח.\p"
	.string "אני מחבב אותך! קח{ADD_YUD} את זה!$"

LavaridgeTown_HerbShop_Text_ExplainCharcoal:
	.string "הפחם שנתתי לך משמש\n"
	.string "לייצור תרופות צמחיות.\p"
	.string "הוא גם עושה נפלאות כאשר מוחזק על ידי\n"
	.string "פוקימון.\p"
	.string "הוא מעלה את עוצמתם של מהלכים מסוג אש\n"
	.string "במידה ניכרת.$"

LavaridgeTown_HerbShop_Text_HerbalMedicineWorksButMonWillDislike:
	.string "תרופות צמחיות עובדות בצורה מרשימה.\n"
	.string "אבל הפוקימון שלך ישנא אותך בגללן.\l"
	.string "הן בטח מרות בצורה איומה!$"

