FortreeCity_House3_MapScripts::
	.byte 0

FortreeCity_House3_EventScript_Maniac::
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_SchoolKidM::
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end

FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
	.string "כשדיברתי על הפוקידע,\n"
	.string "נזכרתי במשהו.\p"
	.string "פגשתי את המאמן הזה, סטיבן,\n"
	.string "כשחיפשתי אבנים נדירות.\p"
	.string "הו, וואו, היו איתו כמה פוקימונים\n"
	.string "מדהימים איתו.\p"
	.string "הם לא היו רק נדירים, הם היו\n"
	.string "מאומנים עד קיצוניות מפחידה!\p"
	.string "ייתכן שהוא אפילו חזק יותר\n"
	.string "ממנהיג המכון בעיר הזו…$"

FortreeCity_House3_Text_OhYouHavePokedex:
	.string "מה זה הדבר הזה שיש לך שם?\p"
	.string "… … … … … …\p"
	.string "או, קוראים לזה פוקידע?\n"
	.string "זה ממש מגניב!$"

