SlateportCity_SternsShipyard_2F_MapScripts::
	.byte 0

SlateportCity_SternsShipyard_2F_EventScript_Scientist1::
	msgbox SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_EventScript_Scientist2::
	msgbox SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy, MSGBOX_NPC
	end

SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding:
	.string "לתכנן ספינה גדולה זה דומה יותר\n"
	.string "לבניית בניין גדול מאשר הרכבת\l"
	.string "כלי תחבורה.$"

SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy:
	.string "לא נראה לך מוזר שספינה עשויה\n"
	.string "ברזל כבד מצליחה לצוף?\p"
	.string "היא צפה בזכות עיקרון הנקרא\n"
	.string "ציפה.$"

