LilycoveCity_House4_MapScripts::
	.byte 0

LilycoveCity_House4_EventScript_Man1::
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2::
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
    .string "המסתורין הגדולים ביותר של הכוכב הזה\n"
    .string "נמצאים בתחתית הים.\p"
    .string "מישהו אמר את זה, אבל אני לא יודע…$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
    .string "יש תעלה עמוקה מתחת למים\n"
    .string "בין מוסדיפ לסוטופוליס.\p"
    .string "כך מישהו סיפר לי, בכל מקרה.$"

